/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner
 */
export interface ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner
     */
    tas: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner
     */
    amount: number;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner(value: object): value is ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner {
    if (!('tas' in value) || value['tas'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tas': json['tas'],
        'amount': json['amount'],
    };
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSON(json: any): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tas': value['tas'],
        'amount': value['amount'],
    };
}

