/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SubawardsPost200ResponsePageMetadata
 */
export interface ApiV2SubawardsPost200ResponsePageMetadata {
    /**
     * 
     * @type {number}
     * @memberof ApiV2SubawardsPost200ResponsePageMetadata
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SubawardsPost200ResponsePageMetadata
     */
    next: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SubawardsPost200ResponsePageMetadata
     */
    previous: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2SubawardsPost200ResponsePageMetadata
     */
    hasNext: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2SubawardsPost200ResponsePageMetadata
     */
    hasPrevious: boolean;
}

/**
 * Check if a given object implements the ApiV2SubawardsPost200ResponsePageMetadata interface.
 */
export function instanceOfApiV2SubawardsPost200ResponsePageMetadata(value: object): value is ApiV2SubawardsPost200ResponsePageMetadata {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('hasPrevious' in value) || value['hasPrevious'] === undefined) return false;
    return true;
}

export function ApiV2SubawardsPost200ResponsePageMetadataFromJSON(json: any): ApiV2SubawardsPost200ResponsePageMetadata {
    return ApiV2SubawardsPost200ResponsePageMetadataFromJSONTyped(json, false);
}

export function ApiV2SubawardsPost200ResponsePageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SubawardsPost200ResponsePageMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'next': json['next'],
        'previous': json['previous'],
        'hasNext': json['hasNext'],
        'hasPrevious': json['hasPrevious'],
    };
}

export function ApiV2SubawardsPost200ResponsePageMetadataToJSON(json: any): ApiV2SubawardsPost200ResponsePageMetadata {
    return ApiV2SubawardsPost200ResponsePageMetadataToJSONTyped(json, false);
}

export function ApiV2SubawardsPost200ResponsePageMetadataToJSONTyped(value?: ApiV2SubawardsPost200ResponsePageMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'next': value['next'],
        'previous': value['previous'],
        'hasNext': value['hasNext'],
        'hasPrevious': value['hasPrevious'],
    };
}

