/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardsFundingRollupPost200Response
 */
export interface ApiV2AwardsFundingRollupPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingRollupPost200Response
     */
    totalTransactionObligatedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingRollupPost200Response
     */
    awardingAgencyCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingRollupPost200Response
     */
    fundingAgencyCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingRollupPost200Response
     */
    federalAccountCount: number;
}

/**
 * Check if a given object implements the ApiV2AwardsFundingRollupPost200Response interface.
 */
export function instanceOfApiV2AwardsFundingRollupPost200Response(value: object): value is ApiV2AwardsFundingRollupPost200Response {
    if (!('totalTransactionObligatedAmount' in value) || value['totalTransactionObligatedAmount'] === undefined) return false;
    if (!('awardingAgencyCount' in value) || value['awardingAgencyCount'] === undefined) return false;
    if (!('fundingAgencyCount' in value) || value['fundingAgencyCount'] === undefined) return false;
    if (!('federalAccountCount' in value) || value['federalAccountCount'] === undefined) return false;
    return true;
}

export function ApiV2AwardsFundingRollupPost200ResponseFromJSON(json: any): ApiV2AwardsFundingRollupPost200Response {
    return ApiV2AwardsFundingRollupPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AwardsFundingRollupPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsFundingRollupPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTransactionObligatedAmount': json['total_transaction_obligated_amount'],
        'awardingAgencyCount': json['awarding_agency_count'],
        'fundingAgencyCount': json['funding_agency_count'],
        'federalAccountCount': json['federal_account_count'],
    };
}

export function ApiV2AwardsFundingRollupPost200ResponseToJSON(json: any): ApiV2AwardsFundingRollupPost200Response {
    return ApiV2AwardsFundingRollupPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AwardsFundingRollupPost200ResponseToJSONTyped(value?: ApiV2AwardsFundingRollupPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_transaction_obligated_amount': value['totalTransactionObligatedAmount'],
        'awarding_agency_count': value['awardingAgencyCount'],
        'funding_agency_count': value['fundingAgencyCount'],
        'federal_account_count': value['federalAccountCount'],
    };
}

