/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BulkDownloadAwardsPost200Response
 */
export interface ApiV2BulkDownloadAwardsPost200Response {
    /**
     * The endpoint used to get the status of a download.
     * @type {string}
     * @memberof ApiV2BulkDownloadAwardsPost200Response
     */
    statusUrl: string;
    /**
     * Is the name of the zipfile containing CSVs that will be generated (file_name is timestamp followed by `_transactions` or `_awards`).
     * @type {string}
     * @memberof ApiV2BulkDownloadAwardsPost200Response
     */
    fileName: string;
    /**
     * The URL for the file.
     * @type {string}
     * @memberof ApiV2BulkDownloadAwardsPost200Response
     */
    fileUrl: string;
    /**
     * The JSON object used when processing the download.
     * @type {object}
     * @memberof ApiV2BulkDownloadAwardsPost200Response
     */
    downloadRequest: object;
}

/**
 * Check if a given object implements the ApiV2BulkDownloadAwardsPost200Response interface.
 */
export function instanceOfApiV2BulkDownloadAwardsPost200Response(value: object): value is ApiV2BulkDownloadAwardsPost200Response {
    if (!('statusUrl' in value) || value['statusUrl'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    if (!('downloadRequest' in value) || value['downloadRequest'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadAwardsPost200ResponseFromJSON(json: any): ApiV2BulkDownloadAwardsPost200Response {
    return ApiV2BulkDownloadAwardsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadAwardsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadAwardsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusUrl': json['status_url'],
        'fileName': json['file_name'],
        'fileUrl': json['file_url'],
        'downloadRequest': json['download_request'],
    };
}

export function ApiV2BulkDownloadAwardsPost200ResponseToJSON(json: any): ApiV2BulkDownloadAwardsPost200Response {
    return ApiV2BulkDownloadAwardsPost200ResponseToJSONTyped(json, false);
}

export function ApiV2BulkDownloadAwardsPost200ResponseToJSONTyped(value?: ApiV2BulkDownloadAwardsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_url': value['statusUrl'],
        'file_name': value['fileName'],
        'file_url': value['fileUrl'],
        'download_request': value['downloadRequest'],
    };
}

