/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AwardsAccountsPost200ResponsePageMetadata } from './ApiV2AwardsAccountsPost200ResponsePageMetadata';
import {
    ApiV2AwardsAccountsPost200ResponsePageMetadataFromJSON,
    ApiV2AwardsAccountsPost200ResponsePageMetadataFromJSONTyped,
    ApiV2AwardsAccountsPost200ResponsePageMetadataToJSON,
    ApiV2AwardsAccountsPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AwardsAccountsPost200ResponsePageMetadata';
import type { ApiV2AwardsAccountsPost200ResponseResultsInner } from './ApiV2AwardsAccountsPost200ResponseResultsInner';
import {
    ApiV2AwardsAccountsPost200ResponseResultsInnerFromJSON,
    ApiV2AwardsAccountsPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AwardsAccountsPost200ResponseResultsInnerToJSON,
    ApiV2AwardsAccountsPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AwardsAccountsPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2AwardsAccountsPost200Response
 */
export interface ApiV2AwardsAccountsPost200Response {
    /**
     * 
     * @type {Array<ApiV2AwardsAccountsPost200ResponseResultsInner>}
     * @memberof ApiV2AwardsAccountsPost200Response
     */
    results: Array<ApiV2AwardsAccountsPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2AwardsAccountsPost200ResponsePageMetadata}
     * @memberof ApiV2AwardsAccountsPost200Response
     */
    pageMetadata: ApiV2AwardsAccountsPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2AwardsAccountsPost200Response interface.
 */
export function instanceOfApiV2AwardsAccountsPost200Response(value: object): value is ApiV2AwardsAccountsPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAccountsPost200ResponseFromJSON(json: any): ApiV2AwardsAccountsPost200Response {
    return ApiV2AwardsAccountsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AwardsAccountsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAccountsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2AwardsAccountsPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2AwardsAccountsPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2AwardsAccountsPost200ResponseToJSON(json: any): ApiV2AwardsAccountsPost200Response {
    return ApiV2AwardsAccountsPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AwardsAccountsPost200ResponseToJSONTyped(value?: ApiV2AwardsAccountsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2AwardsAccountsPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2AwardsAccountsPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

