/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod
 */
export interface ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod {
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod
     */
    fiscalYear: string;
    /**
     * Excluded when grouping by `fiscal_year` or `month`.
     * @type {string}
     * @memberof ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod
     */
    quarter?: string;
    /**
     * Excluded when grouping by `fiscal_year` or `quarter`.
     * @type {string}
     * @memberof ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod
     */
    month?: string;
}

/**
 * Check if a given object implements the ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod interface.
 */
export function instanceOfApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod(value: object): value is ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod {
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    return true;
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSON(json: any): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod {
    return ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSONTyped(json, false);
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'fiscalYear': json['fiscal_year'],
        'quarter': json['quarter'] == null ? undefined : json['quarter'],
        'month': json['month'] == null ? undefined : json['month'],
    };
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSON(json: any): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod {
    return ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSONTyped(json, false);
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSONTyped(value?: ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fiscal_year': value['fiscalYear'],
        'quarter': value['quarter'],
        'month': value['month'],
    };
}

