/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2IdvsFundingPost200ResponseResultsInner
 */
export interface ApiV2IdvsFundingPost200ResponseResultsInner {
    /**
     * Unique internal surrogate identifier for an award.  Deprecated.  Use `generated_unique_award_id`.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    awardId: number;
    /**
     * Unique internal natural identifier for an award.
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    generatedUniqueAwardId: string;
    /**
     * Fiscal year of the submission date.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    reportingFiscalYear: number | null;
    /**
     * Fiscal quarter of the submission date.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    reportingFiscalQuarter: number | null;
    /**
     * Fiscal month of the submission date.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    reportingFiscalMonth: number | null;
    /**
     * True if the submission is quarterly.  False if the submission is monthly.
     * @type {boolean}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    isQuarterlySubmission: boolean | null;
    /**
     * Code indicating whether or not the funding record is associated with a disaster.
     * @type {boolean}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    disasterEmergencyFundCode: boolean | null;
    /**
     * Procurement Instrument Identifier (PIID).
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    piid: string | null;
    /**
     * Internal surrogate identifier of the awarding agency.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    awardingAgencyId: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    awardingToptierAgencyId: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    awardingAgencySlug: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    awardingAgencyName: string | null;
    /**
     * Internal surrogate identifier of the funding agency.
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    fundingAgencyId: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    fundingToptierAgencyId: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    fundingAgencySlug: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    fundingAgencyName: string | null;
    /**
     * CGAC of the funding agency.
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    agencyId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    mainAccountCode: string | null;
    /**
     * Federal Account Title
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    accountTitle: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    programActivityCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    programActivityName: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    objectClass: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    objectClassName: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    transactionObligatedAmount: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsFundingPost200ResponseResultsInner
     */
    grossOutlayAmount: number | null;
}

/**
 * Check if a given object implements the ApiV2IdvsFundingPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2IdvsFundingPost200ResponseResultsInner(value: object): value is ApiV2IdvsFundingPost200ResponseResultsInner {
    if (!('awardId' in value) || value['awardId'] === undefined) return false;
    if (!('generatedUniqueAwardId' in value) || value['generatedUniqueAwardId'] === undefined) return false;
    if (!('reportingFiscalYear' in value) || value['reportingFiscalYear'] === undefined) return false;
    if (!('reportingFiscalQuarter' in value) || value['reportingFiscalQuarter'] === undefined) return false;
    if (!('reportingFiscalMonth' in value) || value['reportingFiscalMonth'] === undefined) return false;
    if (!('isQuarterlySubmission' in value) || value['isQuarterlySubmission'] === undefined) return false;
    if (!('disasterEmergencyFundCode' in value) || value['disasterEmergencyFundCode'] === undefined) return false;
    if (!('piid' in value) || value['piid'] === undefined) return false;
    if (!('awardingAgencyId' in value) || value['awardingAgencyId'] === undefined) return false;
    if (!('awardingToptierAgencyId' in value) || value['awardingToptierAgencyId'] === undefined) return false;
    if (!('awardingAgencySlug' in value) || value['awardingAgencySlug'] === undefined) return false;
    if (!('awardingAgencyName' in value) || value['awardingAgencyName'] === undefined) return false;
    if (!('fundingAgencyId' in value) || value['fundingAgencyId'] === undefined) return false;
    if (!('fundingToptierAgencyId' in value) || value['fundingToptierAgencyId'] === undefined) return false;
    if (!('fundingAgencySlug' in value) || value['fundingAgencySlug'] === undefined) return false;
    if (!('fundingAgencyName' in value) || value['fundingAgencyName'] === undefined) return false;
    if (!('agencyId' in value) || value['agencyId'] === undefined) return false;
    if (!('mainAccountCode' in value) || value['mainAccountCode'] === undefined) return false;
    if (!('accountTitle' in value) || value['accountTitle'] === undefined) return false;
    if (!('programActivityCode' in value) || value['programActivityCode'] === undefined) return false;
    if (!('programActivityName' in value) || value['programActivityName'] === undefined) return false;
    if (!('objectClass' in value) || value['objectClass'] === undefined) return false;
    if (!('objectClassName' in value) || value['objectClassName'] === undefined) return false;
    if (!('transactionObligatedAmount' in value) || value['transactionObligatedAmount'] === undefined) return false;
    if (!('grossOutlayAmount' in value) || value['grossOutlayAmount'] === undefined) return false;
    return true;
}

export function ApiV2IdvsFundingPost200ResponseResultsInnerFromJSON(json: any): ApiV2IdvsFundingPost200ResponseResultsInner {
    return ApiV2IdvsFundingPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2IdvsFundingPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsFundingPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'awardId': json['award_id'],
        'generatedUniqueAwardId': json['generated_unique_award_id'],
        'reportingFiscalYear': json['reporting_fiscal_year'],
        'reportingFiscalQuarter': json['reporting_fiscal_quarter'],
        'reportingFiscalMonth': json['reporting_fiscal_month'],
        'isQuarterlySubmission': json['is_quarterly_submission'],
        'disasterEmergencyFundCode': json['disaster_emergency_fund_code'],
        'piid': json['piid'],
        'awardingAgencyId': json['awarding_agency_id'],
        'awardingToptierAgencyId': json['awarding_toptier_agency_id'],
        'awardingAgencySlug': json['awarding_agency_slug'],
        'awardingAgencyName': json['awarding_agency_name'],
        'fundingAgencyId': json['funding_agency_id'],
        'fundingToptierAgencyId': json['funding_toptier_agency_id'],
        'fundingAgencySlug': json['funding_agency_slug'],
        'fundingAgencyName': json['funding_agency_name'],
        'agencyId': json['agency_id'],
        'mainAccountCode': json['main_account_code'],
        'accountTitle': json['account_title'],
        'programActivityCode': json['program_activity_code'],
        'programActivityName': json['program_activity_name'],
        'objectClass': json['object_class'],
        'objectClassName': json['object_class_name'],
        'transactionObligatedAmount': json['transaction_obligated_amount'],
        'grossOutlayAmount': json['gross_outlay_amount'],
    };
}

export function ApiV2IdvsFundingPost200ResponseResultsInnerToJSON(json: any): ApiV2IdvsFundingPost200ResponseResultsInner {
    return ApiV2IdvsFundingPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2IdvsFundingPost200ResponseResultsInnerToJSONTyped(value?: ApiV2IdvsFundingPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'award_id': value['awardId'],
        'generated_unique_award_id': value['generatedUniqueAwardId'],
        'reporting_fiscal_year': value['reportingFiscalYear'],
        'reporting_fiscal_quarter': value['reportingFiscalQuarter'],
        'reporting_fiscal_month': value['reportingFiscalMonth'],
        'is_quarterly_submission': value['isQuarterlySubmission'],
        'disaster_emergency_fund_code': value['disasterEmergencyFundCode'],
        'piid': value['piid'],
        'awarding_agency_id': value['awardingAgencyId'],
        'awarding_toptier_agency_id': value['awardingToptierAgencyId'],
        'awarding_agency_slug': value['awardingAgencySlug'],
        'awarding_agency_name': value['awardingAgencyName'],
        'funding_agency_id': value['fundingAgencyId'],
        'funding_toptier_agency_id': value['fundingToptierAgencyId'],
        'funding_agency_slug': value['fundingAgencySlug'],
        'funding_agency_name': value['fundingAgencyName'],
        'agency_id': value['agencyId'],
        'main_account_code': value['mainAccountCode'],
        'account_title': value['accountTitle'],
        'program_activity_code': value['programActivityCode'],
        'program_activity_name': value['programActivityName'],
        'object_class': value['objectClass'],
        'object_class_name': value['objectClassName'],
        'transaction_obligated_amount': value['transactionObligatedAmount'],
        'gross_outlay_amount': value['grossOutlayAmount'],
    };
}

