/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInner } from './ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInner';
import {
    ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerFromJSON,
    ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerFromJSONTyped,
    ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerToJSON,
    ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInner';
import type { ApiV2AgencyAwardsCountPost200ResponsePageMetadata } from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';
import {
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSONTyped,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response
 */
export interface ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response {
    /**
     * 
     * @type {Array<ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInner>}
     * @memberof ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response
     */
    results: Array<ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2AgencyAwardsCountPost200ResponsePageMetadata}
     * @memberof ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response
     */
    pageMetadata: ApiV2AgencyAwardsCountPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response interface.
 */
export function instanceOfApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response(value: object): value is ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseFromJSON(json: any): ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response {
    return ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseToJSON(json: any): ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response {
    return ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseToJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseToJSONTyped(value?: ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountCodeProgramActivitiesPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

