/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
 */
export interface ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
     */
    toptierCode: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
     */
    budgetFunctionCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
     */
    budgetSubFunctionCount: number;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response interface.
 */
export function instanceOfApiV2AgencyToptierCodeBudgetFunctionCountPost200Response(value: object): value is ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response {
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('budgetFunctionCount' in value) || value['budgetFunctionCount'] === undefined) return false;
    if (!('budgetSubFunctionCount' in value) || value['budgetSubFunctionCount'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseFromJSON(json: any): ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response {
    return ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'toptierCode': json['toptier_code'],
        'fiscalYear': json['fiscal_year'],
        'budgetFunctionCount': json['budget_function_count'],
        'budgetSubFunctionCount': json['budget_sub_function_count'],
        'messages': json['messages'],
    };
}

export function ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseToJSON(json: any): ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response {
    return ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeBudgetFunctionCountPost200ResponseToJSONTyped(value?: ApiV2AgencyToptierCodeBudgetFunctionCountPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toptier_code': value['toptierCode'],
        'fiscal_year': value['fiscalYear'],
        'budget_function_count': value['budgetFunctionCount'],
        'budget_sub_function_count': value['budgetSubFunctionCount'],
        'messages': value['messages'],
    };
}

