/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner } from './ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner';
import {
    ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSON,
    ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSON,
    ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner';
import type { ApiV2AgencyAwardsCountPost200ResponsePageMetadata } from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';
import {
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSONTyped,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
 */
export interface ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
     */
    treasuryAccountSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {ApiV2AgencyAwardsCountPost200ResponsePageMetadata}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
     */
    pageMetadata: ApiV2AgencyAwardsCountPost200ResponsePageMetadata;
    /**
     * 
     * @type {Array<ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner>}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
     */
    results: Array<ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response interface.
 */
export function instanceOfApiV2AgencyTreasuryAccountTasProgramActivityPost200Response(value: object): value is ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response {
    if (!('treasuryAccountSymbol' in value) || value['treasuryAccountSymbol'] === undefined) return false;
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseFromJSON(json: any): ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response {
    return ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'treasuryAccountSymbol': json['treasury_account_symbol'],
        'fiscalYear': json['fiscal_year'],
        'pageMetadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'results': ((json['results'] as Array<any>).map(ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'],
    };
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseToJSON(json: any): ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response {
    return ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseToJSONTyped(value?: ApiV2AgencyTreasuryAccountTasProgramActivityPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'treasury_account_symbol': value['treasuryAccountSymbol'],
        'fiscal_year': value['fiscalYear'],
        'page_metadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'results': ((value['results'] as Array<any>).map(ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

