/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompleteNaicsPost200ResponseResultsInner
 */
export interface ApiV2AutocompleteNaicsPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteNaicsPost200ResponseResultsInner
     */
    naics: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteNaicsPost200ResponseResultsInner
     */
    naicsDescription: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AutocompleteNaicsPost200ResponseResultsInner
     */
    yearRetired: number | null;
}

/**
 * Check if a given object implements the ApiV2AutocompleteNaicsPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2AutocompleteNaicsPost200ResponseResultsInner(value: object): value is ApiV2AutocompleteNaicsPost200ResponseResultsInner {
    if (!('naics' in value) || value['naics'] === undefined) return false;
    if (!('naicsDescription' in value) || value['naicsDescription'] === undefined) return false;
    if (!('yearRetired' in value) || value['yearRetired'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteNaicsPost200ResponseResultsInnerFromJSON(json: any): ApiV2AutocompleteNaicsPost200ResponseResultsInner {
    return ApiV2AutocompleteNaicsPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2AutocompleteNaicsPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteNaicsPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'naics': json['naics'],
        'naicsDescription': json['naics_description'],
        'yearRetired': json['year_retired'],
    };
}

export function ApiV2AutocompleteNaicsPost200ResponseResultsInnerToJSON(json: any): ApiV2AutocompleteNaicsPost200ResponseResultsInner {
    return ApiV2AutocompleteNaicsPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2AutocompleteNaicsPost200ResponseResultsInnerToJSONTyped(value?: ApiV2AutocompleteNaicsPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'naics': value['naics'],
        'naics_description': value['naicsDescription'],
        'year_retired': value['yearRetired'],
    };
}

