/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterAgencyLoansPost200ResponsePageMetadata } from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import {
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import type { ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner } from './ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner';
import {
    ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSON,
    ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSONTyped,
    ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSON,
    ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response
 */
export interface ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response {
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponsePageMetadata}
     * @memberof ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response
     */
    pageMetadata: ApiV2DisasterAgencyLoansPost200ResponsePageMetadata;
    /**
     * 
     * @type {Array<ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner>}
     * @memberof ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response
     */
    results: Array<ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response(value: object): value is ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response {
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response {
    return ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageMetadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'results': ((json['results'] as Array<any>).map(ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseToJSON(json: any): ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response {
    return ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_metadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'results': ((value['results'] as Array<any>).map(ApiV2ReportingAgenciesToptierCodeDiscrepanciesPost200ResponseResultsInnerToJSON)),
    };
}

