/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
 */
export interface ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner {
    /**
     * The id is the database key.
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    name: string | null;
    /**
     * `code` is a user-displayable code (such as a program activity or NAICS code, but **not** a database ID). When no such code is relevant, return a `null`.
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    code: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    totalOutlays: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner
     */
    yearRetired: number | null;
}

/**
 * Check if a given object implements the ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner(value: object): value is ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('totalOutlays' in value) || value['totalOutlays'] === undefined) return false;
    if (!('yearRetired' in value) || value['yearRetired'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerFromJSON(json: any): ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner {
    return ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'amount': json['amount'],
        'totalOutlays': json['total_outlays'],
        'yearRetired': json['year_retired'],
    };
}

export function ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerToJSON(json: any): ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner {
    return ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInnerToJSONTyped(value?: ApiV2SearchSpendingByCategoryNaicsPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'amount': value['amount'],
        'total_outlays': value['totalOutlays'],
        'year_retired': value['yearRetired'],
    };
}

