/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReferencesAwardTypesPost200ResponseGrants
 */
export interface ApiV2ReferencesAwardTypesPost200ResponseGrants {
    /**
     * Block Grant
     * @type {string}
     * @memberof ApiV2ReferencesAwardTypesPost200ResponseGrants
     */
    _02: string;
    /**
     * Formula Grant
     * @type {string}
     * @memberof ApiV2ReferencesAwardTypesPost200ResponseGrants
     */
    _03: string;
    /**
     * Project Grant
     * @type {string}
     * @memberof ApiV2ReferencesAwardTypesPost200ResponseGrants
     */
    _04: string;
    /**
     * Cooperative Agreement
     * @type {string}
     * @memberof ApiV2ReferencesAwardTypesPost200ResponseGrants
     */
    _05: string;
}

/**
 * Check if a given object implements the ApiV2ReferencesAwardTypesPost200ResponseGrants interface.
 */
export function instanceOfApiV2ReferencesAwardTypesPost200ResponseGrants(value: object): value is ApiV2ReferencesAwardTypesPost200ResponseGrants {
    if (!('_02' in value) || value['_02'] === undefined) return false;
    if (!('_03' in value) || value['_03'] === undefined) return false;
    if (!('_04' in value) || value['_04'] === undefined) return false;
    if (!('_05' in value) || value['_05'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesAwardTypesPost200ResponseGrantsFromJSON(json: any): ApiV2ReferencesAwardTypesPost200ResponseGrants {
    return ApiV2ReferencesAwardTypesPost200ResponseGrantsFromJSONTyped(json, false);
}

export function ApiV2ReferencesAwardTypesPost200ResponseGrantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesAwardTypesPost200ResponseGrants {
    if (json == null) {
        return json;
    }
    return {
        
        '_02': json['02'],
        '_03': json['03'],
        '_04': json['04'],
        '_05': json['05'],
    };
}

export function ApiV2ReferencesAwardTypesPost200ResponseGrantsToJSON(json: any): ApiV2ReferencesAwardTypesPost200ResponseGrants {
    return ApiV2ReferencesAwardTypesPost200ResponseGrantsToJSONTyped(json, false);
}

export function ApiV2ReferencesAwardTypesPost200ResponseGrantsToJSONTyped(value?: ApiV2ReferencesAwardTypesPost200ResponseGrants | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '02': value['_02'],
        '03': value['_03'],
        '04': value['_04'],
        '05': value['_05'],
    };
}

