/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2FederalObligationsPost200ResponsePageMetadata } from './ApiV2FederalObligationsPost200ResponsePageMetadata';
import {
    ApiV2FederalObligationsPost200ResponsePageMetadataFromJSON,
    ApiV2FederalObligationsPost200ResponsePageMetadataFromJSONTyped,
    ApiV2FederalObligationsPost200ResponsePageMetadataToJSON,
    ApiV2FederalObligationsPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2FederalObligationsPost200ResponsePageMetadata';
import type { ApiV2FederalObligationsPost200ResponseResultsInner } from './ApiV2FederalObligationsPost200ResponseResultsInner';
import {
    ApiV2FederalObligationsPost200ResponseResultsInnerFromJSON,
    ApiV2FederalObligationsPost200ResponseResultsInnerFromJSONTyped,
    ApiV2FederalObligationsPost200ResponseResultsInnerToJSON,
    ApiV2FederalObligationsPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2FederalObligationsPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2FederalObligationsPost200Response
 */
export interface ApiV2FederalObligationsPost200Response {
    /**
     * 
     * @type {Array<ApiV2FederalObligationsPost200ResponseResultsInner>}
     * @memberof ApiV2FederalObligationsPost200Response
     */
    results: Array<ApiV2FederalObligationsPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2FederalObligationsPost200ResponsePageMetadata}
     * @memberof ApiV2FederalObligationsPost200Response
     */
    pageMetadata: ApiV2FederalObligationsPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2FederalObligationsPost200Response interface.
 */
export function instanceOfApiV2FederalObligationsPost200Response(value: object): value is ApiV2FederalObligationsPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2FederalObligationsPost200ResponseFromJSON(json: any): ApiV2FederalObligationsPost200Response {
    return ApiV2FederalObligationsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2FederalObligationsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalObligationsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2FederalObligationsPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2FederalObligationsPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2FederalObligationsPost200ResponseToJSON(json: any): ApiV2FederalObligationsPost200Response {
    return ApiV2FederalObligationsPost200ResponseToJSONTyped(json, false);
}

export function ApiV2FederalObligationsPost200ResponseToJSONTyped(value?: ApiV2FederalObligationsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2FederalObligationsPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2FederalObligationsPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

