/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
 */
export interface ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
     */
    abbreviation: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
     */
    name: string;
    /**
     * 
     * @type {Array<string | null>}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
     */
    subtierAgencies: Array<string | null>;
    /**
     * 
     * @type {Array<string | null>}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency
     */
    offices: Array<string | null>;
}

/**
 * Check if a given object implements the ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency interface.
 */
export function instanceOfApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency(value: object): value is ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency {
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('subtierAgencies' in value) || value['subtierAgencies'] === undefined) return false;
    if (!('offices' in value) || value['offices'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyFromJSON(json: any): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency {
    return ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyFromJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency {
    if (json == null) {
        return json;
    }
    return {
        
        'abbreviation': json['abbreviation'],
        'code': json['code'],
        'name': json['name'],
        'subtierAgencies': json['subtier_agencies'],
        'offices': json['offices'],
    };
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyToJSON(json: any): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency {
    return ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyToJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgencyToJSONTyped(value?: ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerToptierAgency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abbreviation': value['abbreviation'],
        'code': value['code'],
        'name': value['name'],
        'subtier_agencies': value['subtierAgencies'],
        'offices': value['offices'],
    };
}

