/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterAgencyLoansPost200ResponsePageMetadata } from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import {
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import type { ApiV2DisasterAgencyLoansPost200ResponseTotals } from './ApiV2DisasterAgencyLoansPost200ResponseTotals';
import {
    ApiV2DisasterAgencyLoansPost200ResponseTotalsFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponseTotalsFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponseTotalsToJSON,
    ApiV2DisasterAgencyLoansPost200ResponseTotalsToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponseTotals';
import type { ApiV2DisasterAgencyLoansPost200ResponseResultsInner } from './ApiV2DisasterAgencyLoansPost200ResponseResultsInner';
import {
    ApiV2DisasterAgencyLoansPost200ResponseResultsInnerFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponseResultsInnerFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponseResultsInnerToJSON,
    ApiV2DisasterAgencyLoansPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2DisasterAgencyLoansPost200Response
 */
export interface ApiV2DisasterAgencyLoansPost200Response {
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponseTotals}
     * @memberof ApiV2DisasterAgencyLoansPost200Response
     */
    totals: ApiV2DisasterAgencyLoansPost200ResponseTotals;
    /**
     * 
     * @type {Array<ApiV2DisasterAgencyLoansPost200ResponseResultsInner>}
     * @memberof ApiV2DisasterAgencyLoansPost200Response
     */
    results: Array<ApiV2DisasterAgencyLoansPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponsePageMetadata}
     * @memberof ApiV2DisasterAgencyLoansPost200Response
     */
    pageMetadata: ApiV2DisasterAgencyLoansPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2DisasterAgencyLoansPost200Response interface.
 */
export function instanceOfApiV2DisasterAgencyLoansPost200Response(value: object): value is ApiV2DisasterAgencyLoansPost200Response {
    if (!('totals' in value) || value['totals'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2DisasterAgencyLoansPost200ResponseFromJSON(json: any): ApiV2DisasterAgencyLoansPost200Response {
    return ApiV2DisasterAgencyLoansPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2DisasterAgencyLoansPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterAgencyLoansPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totals': ApiV2DisasterAgencyLoansPost200ResponseTotalsFromJSON(json['totals']),
        'results': ((json['results'] as Array<any>).map(ApiV2DisasterAgencyLoansPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2DisasterAgencyLoansPost200ResponseToJSON(json: any): ApiV2DisasterAgencyLoansPost200Response {
    return ApiV2DisasterAgencyLoansPost200ResponseToJSONTyped(json, false);
}

export function ApiV2DisasterAgencyLoansPost200ResponseToJSONTyped(value?: ApiV2DisasterAgencyLoansPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totals': ApiV2DisasterAgencyLoansPost200ResponseTotalsToJSON(value['totals']),
        'results': ((value['results'] as Array<any>).map(ApiV2DisasterAgencyLoansPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

