/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompletePscPost200ResponseResultsInner
 */
export interface ApiV2AutocompletePscPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompletePscPost200ResponseResultsInner
     */
    productOrServiceCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompletePscPost200ResponseResultsInner
     */
    pscDescription: string;
}

/**
 * Check if a given object implements the ApiV2AutocompletePscPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2AutocompletePscPost200ResponseResultsInner(value: object): value is ApiV2AutocompletePscPost200ResponseResultsInner {
    if (!('productOrServiceCode' in value) || value['productOrServiceCode'] === undefined) return false;
    if (!('pscDescription' in value) || value['pscDescription'] === undefined) return false;
    return true;
}

export function ApiV2AutocompletePscPost200ResponseResultsInnerFromJSON(json: any): ApiV2AutocompletePscPost200ResponseResultsInner {
    return ApiV2AutocompletePscPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2AutocompletePscPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompletePscPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'productOrServiceCode': json['product_or_service_code'],
        'pscDescription': json['psc_description'],
    };
}

export function ApiV2AutocompletePscPost200ResponseResultsInnerToJSON(json: any): ApiV2AutocompletePscPost200ResponseResultsInner {
    return ApiV2AutocompletePscPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2AutocompletePscPost200ResponseResultsInnerToJSONTyped(value?: ApiV2AutocompletePscPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_or_service_code': value['productOrServiceCode'],
        'psc_description': value['pscDescription'],
    };
}

