/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner } from './ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner';
import {
    ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSON,
    ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSONTyped,
    ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSON,
    ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner';
import type { ApiV2SearchSpendingByCategoryPost200ResponsePageMetadata } from './ApiV2SearchSpendingByCategoryPost200ResponsePageMetadata';
import {
    ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataFromJSON,
    ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataFromJSONTyped,
    ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataToJSON,
    ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2SearchSpendingByCategoryPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
 */
export interface ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    category: string;
    /**
     * Spending level value that was provided in the request.
     * @type {ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    spendingLevel: ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum;
    /**
     * 
     * @type {Array<ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner>}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    results: Array<ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner>;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    limit: number;
    /**
     * 
     * @type {ApiV2SearchSpendingByCategoryPost200ResponsePageMetadata}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    pageMetadata?: ApiV2SearchSpendingByCategoryPost200ResponsePageMetadata;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string | null>}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response
     */
    messages?: Array<string | null>;
}


/**
 * @export
 */
export const ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum = {
    Transactions: 'transactions',
    Awards: 'awards',
    Subawards: 'subawards'
} as const;
export type ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum = typeof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum[keyof typeof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseSpendingLevelEnum];


/**
 * Check if a given object implements the ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response interface.
 */
export function instanceOfApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response(value: object): value is ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('spendingLevel' in value) || value['spendingLevel'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseFromJSON(json: any): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response {
    return ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'spendingLevel': json['spending_level'],
        'results': ((json['results'] as Array<any>).map(ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSON)),
        'limit': json['limit'],
        'pageMetadata': json['page_metadata'] == null ? undefined : ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseToJSON(json: any): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response {
    return ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseToJSONTyped(value?: ApiV2SearchSpendingByCategoryAwardingSubagencyPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'spending_level': value['spendingLevel'],
        'results': ((value['results'] as Array<any>).map(ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSON)),
        'limit': value['limit'],
        'page_metadata': ApiV2SearchSpendingByCategoryPost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'messages': value['messages'],
    };
}

