/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner } from './ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner';
import {
    ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSON,
    ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped,
    ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSON,
    ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2DisasterSpendingByGeographyPost200Response
 */
export interface ApiV2DisasterSpendingByGeographyPost200Response {
    /**
     * 
     * @type {ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum}
     * @memberof ApiV2DisasterSpendingByGeographyPost200Response
     */
    geoLayer: ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum;
    /**
     * When fetching transactions, use the primary place of performance or recipient location
     * @type {ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum}
     * @memberof ApiV2DisasterSpendingByGeographyPost200Response
     */
    scope: ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum;
    /**
     * 
     * @type {ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum}
     * @memberof ApiV2DisasterSpendingByGeographyPost200Response
     */
    spendingType: ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum;
    /**
     * 
     * @type {Array<ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner>}
     * @memberof ApiV2DisasterSpendingByGeographyPost200Response
     */
    results?: Array<ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner>;
}


/**
 * @export
 */
export const ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum = {
    State: 'state',
    County: 'county',
    District: 'district'
} as const;
export type ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum = typeof ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum[keyof typeof ApiV2DisasterSpendingByGeographyPost200ResponseGeoLayerEnum];

/**
 * @export
 */
export const ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum = {
    PlaceOfPerformance: 'place_of_performance',
    RecipientLocation: 'recipient_location'
} as const;
export type ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum = typeof ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum[keyof typeof ApiV2DisasterSpendingByGeographyPost200ResponseScopeEnum];

/**
 * @export
 */
export const ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum = {
    Obligation: 'obligation',
    Outlay: 'outlay',
    FaceValueOfLoan: 'face_value_of_loan'
} as const;
export type ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum = typeof ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum[keyof typeof ApiV2DisasterSpendingByGeographyPost200ResponseSpendingTypeEnum];


/**
 * Check if a given object implements the ApiV2DisasterSpendingByGeographyPost200Response interface.
 */
export function instanceOfApiV2DisasterSpendingByGeographyPost200Response(value: object): value is ApiV2DisasterSpendingByGeographyPost200Response {
    if (!('geoLayer' in value) || value['geoLayer'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('spendingType' in value) || value['spendingType'] === undefined) return false;
    return true;
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseFromJSON(json: any): ApiV2DisasterSpendingByGeographyPost200Response {
    return ApiV2DisasterSpendingByGeographyPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterSpendingByGeographyPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'geoLayer': json['geo_layer'],
        'scope': json['scope'],
        'spendingType': json['spending_type'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseToJSON(json: any): ApiV2DisasterSpendingByGeographyPost200Response {
    return ApiV2DisasterSpendingByGeographyPost200ResponseToJSONTyped(json, false);
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseToJSONTyped(value?: ApiV2DisasterSpendingByGeographyPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geo_layer': value['geoLayer'],
        'scope': value['scope'],
        'spending_type': value['spendingType'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSON)),
    };
}

