/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner
 */
export interface ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner
     */
    toptierCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner
     */
    toptierAgencyId: number;
}

/**
 * Check if a given object implements the ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner interface.
 */
export function instanceOfApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner(value: object): value is ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner {
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('toptierAgencyId' in value) || value['toptierAgencyId'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner {
    return ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'toptierCode': json['toptier_code'],
        'name': json['name'],
        'toptierAgencyId': json['toptier_agency_id'],
    };
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner {
    return ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSONTyped(value?: ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toptier_code': value['toptierCode'],
        'name': value['name'],
        'toptier_agency_id': value['toptierAgencyId'],
    };
}

