/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner
 */
export interface ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner
     */
    tas: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner
     */
    fileAObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner
     */
    fileBObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner
     */
    difference: number;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner(value: object): value is ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner {
    if (!('tas' in value) || value['tas'] === undefined) return false;
    if (!('fileAObligation' in value) || value['fileAObligation'] === undefined) return false;
    if (!('fileBObligation' in value) || value['fileBObligation'] === undefined) return false;
    if (!('difference' in value) || value['difference'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tas': json['tas'],
        'fileAObligation': json['file_a_obligation'],
        'fileBObligation': json['file_b_obligation'],
        'difference': json['difference'],
    };
}

export function ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerToJSON(json: any): ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeDifferencesPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tas': value['tas'],
        'file_a_obligation': value['fileAObligation'],
        'file_b_obligation': value['fileBObligation'],
        'difference': value['difference'],
    };
}

