/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2IdvsActivityPost200ResponseResultsInner
 */
export interface ApiV2IdvsActivityPost200ResponseResultsInner {
    /**
     * Unique internal surrogate identifier for an award.  Deprecated.  Use `generated_unique_award_id`.
     * @type {number}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    awardId: number;
    /**
     * Unique internal natural identifier for an award.
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    generatedUniqueAwardId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    awardingAgency: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    awardingAgencyId: number;
    /**
     * `agency_slug` is a string used to generate a link to the agency profile page. Will be `NULL` if the agency does not have a profile page.
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    awardingAgencySlug: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    periodOfPerformancePotentialEndDate: string | null;
    /**
     * Internal, surrogate id for the award's parent.  Deprecated.  Use `parent_generated_unique_award_id`.
     * @type {number}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    parentAwardId: number | null;
    /**
     * Unique internal natural identifier for the award's parent.
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    parentGeneratedUniqueAwardId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    parentAwardPiid: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    obligatedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    awardedAmount: number;
    /**
     * The starting date of the award in the format `YYYY-MM-DD`
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    periodOfPerformanceStartDate: string | null;
    /**
     * Procurement Instrument Identifier (PIID).
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    piid: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    recipientName: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    recipientId: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2IdvsActivityPost200ResponseResultsInner
     */
    grandchild: boolean;
}

/**
 * Check if a given object implements the ApiV2IdvsActivityPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2IdvsActivityPost200ResponseResultsInner(value: object): value is ApiV2IdvsActivityPost200ResponseResultsInner {
    if (!('awardId' in value) || value['awardId'] === undefined) return false;
    if (!('generatedUniqueAwardId' in value) || value['generatedUniqueAwardId'] === undefined) return false;
    if (!('awardingAgency' in value) || value['awardingAgency'] === undefined) return false;
    if (!('awardingAgencyId' in value) || value['awardingAgencyId'] === undefined) return false;
    if (!('awardingAgencySlug' in value) || value['awardingAgencySlug'] === undefined) return false;
    if (!('periodOfPerformancePotentialEndDate' in value) || value['periodOfPerformancePotentialEndDate'] === undefined) return false;
    if (!('parentAwardId' in value) || value['parentAwardId'] === undefined) return false;
    if (!('parentGeneratedUniqueAwardId' in value) || value['parentGeneratedUniqueAwardId'] === undefined) return false;
    if (!('parentAwardPiid' in value) || value['parentAwardPiid'] === undefined) return false;
    if (!('obligatedAmount' in value) || value['obligatedAmount'] === undefined) return false;
    if (!('awardedAmount' in value) || value['awardedAmount'] === undefined) return false;
    if (!('periodOfPerformanceStartDate' in value) || value['periodOfPerformanceStartDate'] === undefined) return false;
    if (!('piid' in value) || value['piid'] === undefined) return false;
    if (!('recipientName' in value) || value['recipientName'] === undefined) return false;
    if (!('recipientId' in value) || value['recipientId'] === undefined) return false;
    if (!('grandchild' in value) || value['grandchild'] === undefined) return false;
    return true;
}

export function ApiV2IdvsActivityPost200ResponseResultsInnerFromJSON(json: any): ApiV2IdvsActivityPost200ResponseResultsInner {
    return ApiV2IdvsActivityPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2IdvsActivityPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsActivityPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'awardId': json['award_id'],
        'generatedUniqueAwardId': json['generated_unique_award_id'],
        'awardingAgency': json['awarding_agency'],
        'awardingAgencyId': json['awarding_agency_id'],
        'awardingAgencySlug': json['awarding_agency_slug'],
        'periodOfPerformancePotentialEndDate': json['period_of_performance_potential_end_date'],
        'parentAwardId': json['parent_award_id'],
        'parentGeneratedUniqueAwardId': json['parent_generated_unique_award_id'],
        'parentAwardPiid': json['parent_award_piid'],
        'obligatedAmount': json['obligated_amount'],
        'awardedAmount': json['awarded_amount'],
        'periodOfPerformanceStartDate': json['period_of_performance_start_date'],
        'piid': json['piid'],
        'recipientName': json['recipient_name'],
        'recipientId': json['recipient_id'],
        'grandchild': json['grandchild'],
    };
}

export function ApiV2IdvsActivityPost200ResponseResultsInnerToJSON(json: any): ApiV2IdvsActivityPost200ResponseResultsInner {
    return ApiV2IdvsActivityPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2IdvsActivityPost200ResponseResultsInnerToJSONTyped(value?: ApiV2IdvsActivityPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'award_id': value['awardId'],
        'generated_unique_award_id': value['generatedUniqueAwardId'],
        'awarding_agency': value['awardingAgency'],
        'awarding_agency_id': value['awardingAgencyId'],
        'awarding_agency_slug': value['awardingAgencySlug'],
        'period_of_performance_potential_end_date': value['periodOfPerformancePotentialEndDate'],
        'parent_award_id': value['parentAwardId'],
        'parent_generated_unique_award_id': value['parentGeneratedUniqueAwardId'],
        'parent_award_piid': value['parentAwardPiid'],
        'obligated_amount': value['obligatedAmount'],
        'awarded_amount': value['awardedAmount'],
        'period_of_performance_start_date': value['periodOfPerformanceStartDate'],
        'piid': value['piid'],
        'recipient_name': value['recipientName'],
        'recipient_id': value['recipientId'],
        'grandchild': value['grandchild'],
    };
}

