/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner } from './ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner';
import {
    ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSON,
    ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSONTyped,
    ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSON,
    ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2ReferencesAssistanceListingCodeFilterPost200Response
 */
export interface ApiV2ReferencesAssistanceListingCodeFilterPost200Response {
    /**
     * 
     * @type {Array<ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner>}
     * @memberof ApiV2ReferencesAssistanceListingCodeFilterPost200Response
     */
    results: Array<ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2ReferencesAssistanceListingCodeFilterPost200Response interface.
 */
export function instanceOfApiV2ReferencesAssistanceListingCodeFilterPost200Response(value: object): value is ApiV2ReferencesAssistanceListingCodeFilterPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseFromJSON(json: any): ApiV2ReferencesAssistanceListingCodeFilterPost200Response {
    return ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesAssistanceListingCodeFilterPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseToJSON(json: any): ApiV2ReferencesAssistanceListingCodeFilterPost200Response {
    return ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseToJSONTyped(json, false);
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseToJSONTyped(value?: ApiV2ReferencesAssistanceListingCodeFilterPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSON)),
    };
}

