/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AutocompleteAccountsAidPost200ResponseResultsInner } from './ApiV2AutocompleteAccountsAidPost200ResponseResultsInner';
import {
    ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerFromJSON,
    ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerToJSON,
    ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AutocompleteAccountsAidPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2AutocompleteAccountsAidPost200Response
 */
export interface ApiV2AutocompleteAccountsAidPost200Response {
    /**
     * 
     * @type {Array<ApiV2AutocompleteAccountsAidPost200ResponseResultsInner>}
     * @memberof ApiV2AutocompleteAccountsAidPost200Response
     */
    results: Array<ApiV2AutocompleteAccountsAidPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2AutocompleteAccountsAidPost200Response interface.
 */
export function instanceOfApiV2AutocompleteAccountsAidPost200Response(value: object): value is ApiV2AutocompleteAccountsAidPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteAccountsAidPost200ResponseFromJSON(json: any): ApiV2AutocompleteAccountsAidPost200Response {
    return ApiV2AutocompleteAccountsAidPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AutocompleteAccountsAidPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteAccountsAidPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2AutocompleteAccountsAidPost200ResponseToJSON(json: any): ApiV2AutocompleteAccountsAidPost200Response {
    return ApiV2AutocompleteAccountsAidPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AutocompleteAccountsAidPost200ResponseToJSONTyped(value?: ApiV2AutocompleteAccountsAidPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2AutocompleteAccountsAidPost200ResponseResultsInnerToJSON)),
    };
}

