/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode } from './ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode';
import {
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSON,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSON,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode';

/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200ResponsePscHierarchy
 */
export interface ApiV2AwardsAwardIdPost200ResponsePscHierarchy {
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode}
     * @memberof ApiV2AwardsAwardIdPost200ResponsePscHierarchy
     */
    toptierCode: ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode}
     * @memberof ApiV2AwardsAwardIdPost200ResponsePscHierarchy
     */
    midtierCode: ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode}
     * @memberof ApiV2AwardsAwardIdPost200ResponsePscHierarchy
     */
    subtierCode: ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode}
     * @memberof ApiV2AwardsAwardIdPost200ResponsePscHierarchy
     */
    baseCode: ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCode;
}

/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200ResponsePscHierarchy interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200ResponsePscHierarchy(value: object): value is ApiV2AwardsAwardIdPost200ResponsePscHierarchy {
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('midtierCode' in value) || value['midtierCode'] === undefined) return false;
    if (!('subtierCode' in value) || value['subtierCode'] === undefined) return false;
    if (!('baseCode' in value) || value['baseCode'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSON(json: any): ApiV2AwardsAwardIdPost200ResponsePscHierarchy {
    return ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200ResponsePscHierarchy {
    if (json == null) {
        return json;
    }
    return {
        
        'toptierCode': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSON(json['toptier_code']),
        'midtierCode': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSON(json['midtier_code']),
        'subtierCode': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSON(json['subtier_code']),
        'baseCode': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeFromJSON(json['base_code']),
    };
}

export function ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSON(json: any): ApiV2AwardsAwardIdPost200ResponsePscHierarchy {
    return ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSONTyped(value?: ApiV2AwardsAwardIdPost200ResponsePscHierarchy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toptier_code': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSON(value['toptierCode']),
        'midtier_code': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSON(value['midtierCode']),
        'subtier_code': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSON(value['subtierCode']),
        'base_code': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToptierCodeToJSON(value['baseCode']),
    };
}

