/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompleteAccountsAPost200Response
 */
export interface ApiV2AutocompleteAccountsAPost200Response {
    /**
     * 
     * @type {Array<string | null>}
     * @memberof ApiV2AutocompleteAccountsAPost200Response
     */
    results: Array<string | null>;
}

/**
 * Check if a given object implements the ApiV2AutocompleteAccountsAPost200Response interface.
 */
export function instanceOfApiV2AutocompleteAccountsAPost200Response(value: object): value is ApiV2AutocompleteAccountsAPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteAccountsAPost200ResponseFromJSON(json: any): ApiV2AutocompleteAccountsAPost200Response {
    return ApiV2AutocompleteAccountsAPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AutocompleteAccountsAPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteAccountsAPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'],
    };
}

export function ApiV2AutocompleteAccountsAPost200ResponseToJSON(json: any): ApiV2AutocompleteAccountsAPost200Response {
    return ApiV2AutocompleteAccountsAPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AutocompleteAccountsAPost200ResponseToJSONTyped(value?: ApiV2AutocompleteAccountsAPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'],
    };
}

