/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner
 */
export interface ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner
     */
    subtierAgencyName: string;
}

/**
 * Check if a given object implements the ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner interface.
 */
export function instanceOfApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner(value: object): value is ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner {
    if (!('subtierAgencyName' in value) || value['subtierAgencyName'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner {
    return ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'subtierAgencyName': json['subtier_agency_name'],
    };
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner {
    return ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSONTyped(value?: ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subtier_agency_name': value['subtierAgencyName'],
    };
}

