/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInner } from './ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInner';
import {
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerFromJSON,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerFromJSONTyped,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerToJSON,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerToJSONTyped,
} from './ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInner';

/**
 * 
 * @export
 * @interface ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
 */
export interface ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
     */
    obligatedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
     */
    grossOutlayAmount: number;
    /**
     * Indicates whether the values come from the Program Activity Reporting Key (PARK) or Program Activity Code/Name (PAC/PAN)
     * @type {ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
     */
    type: ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum;
    /**
     * 
     * @type {Array<ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInner>}
     * @memberof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner
     */
    children: Array<ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInner>;
}


/**
 * @export
 */
export const ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum = {
    PacPan: 'PAC/PAN',
    Park: 'PARK'
} as const;
export type ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum = typeof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum[keyof typeof ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerTypeEnum];


/**
 * Check if a given object implements the ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner(value: object): value is ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('obligatedAmount' in value) || value['obligatedAmount'] === undefined) return false;
    if (!('grossOutlayAmount' in value) || value['grossOutlayAmount'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    return true;
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSON(json: any): ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner {
    return ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'obligatedAmount': json['obligated_amount'],
        'grossOutlayAmount': json['gross_outlay_amount'],
        'type': json['type'],
        'children': ((json['children'] as Array<any>).map(ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerFromJSON)),
    };
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSON(json: any): ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner {
    return ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInnerToJSONTyped(value?: ApiV2AgencyTreasuryAccountTasProgramActivityPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'obligated_amount': value['obligatedAmount'],
        'gross_outlay_amount': value['grossOutlayAmount'],
        'type': value['type'],
        'children': ((value['children'] as Array<any>).map(ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerChildrenInnerToJSON)),
    };
}

