/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompleteCfdaPost200ResponseResultsInner
 */
export interface ApiV2AutocompleteCfdaPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteCfdaPost200ResponseResultsInner
     */
    popularName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteCfdaPost200ResponseResultsInner
     */
    programNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteCfdaPost200ResponseResultsInner
     */
    programTitle: string;
}

/**
 * Check if a given object implements the ApiV2AutocompleteCfdaPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2AutocompleteCfdaPost200ResponseResultsInner(value: object): value is ApiV2AutocompleteCfdaPost200ResponseResultsInner {
    if (!('popularName' in value) || value['popularName'] === undefined) return false;
    if (!('programNumber' in value) || value['programNumber'] === undefined) return false;
    if (!('programTitle' in value) || value['programTitle'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteCfdaPost200ResponseResultsInnerFromJSON(json: any): ApiV2AutocompleteCfdaPost200ResponseResultsInner {
    return ApiV2AutocompleteCfdaPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2AutocompleteCfdaPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteCfdaPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'popularName': json['popular_name'],
        'programNumber': json['program_number'],
        'programTitle': json['program_title'],
    };
}

export function ApiV2AutocompleteCfdaPost200ResponseResultsInnerToJSON(json: any): ApiV2AutocompleteCfdaPost200ResponseResultsInner {
    return ApiV2AutocompleteCfdaPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2AutocompleteCfdaPost200ResponseResultsInnerToJSONTyped(value?: ApiV2AutocompleteCfdaPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'popular_name': value['popularName'],
        'program_number': value['programNumber'],
        'program_title': value['programTitle'],
    };
}

