/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
 */
export interface ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner {
    /**
     * The id is the database key.
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    name: string | null;
    /**
     * `code` is a user-displayable code (such as a program activity or NAICS code, but **not** a database ID). When no such code is relevant, return a `null`. This `code` refers to the subtier agency abbreviation.
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    code: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    subagencySlug: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    agencyId: number;
    /**
     * The `agency_abbreviation` refers to the abbreviation for the toptier agency associated with the subtier agency.
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    agencyAbbreviation: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    agencyName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    agencySlug: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner
     */
    totalOutlays: number | null;
}

/**
 * Check if a given object implements the ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner(value: object): value is ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('subagencySlug' in value) || value['subagencySlug'] === undefined) return false;
    if (!('agencyId' in value) || value['agencyId'] === undefined) return false;
    if (!('agencyAbbreviation' in value) || value['agencyAbbreviation'] === undefined) return false;
    if (!('agencyName' in value) || value['agencyName'] === undefined) return false;
    if (!('agencySlug' in value) || value['agencySlug'] === undefined) return false;
    if (!('totalOutlays' in value) || value['totalOutlays'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSON(json: any): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner {
    return ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'amount': json['amount'],
        'subagencySlug': json['subagency_slug'],
        'agencyId': json['agency_id'],
        'agencyAbbreviation': json['agency_abbreviation'],
        'agencyName': json['agency_name'],
        'agencySlug': json['agency_slug'],
        'totalOutlays': json['total_outlays'],
    };
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSON(json: any): ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner {
    return ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInnerToJSONTyped(value?: ApiV2SearchSpendingByCategoryAwardingSubagencyPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'amount': value['amount'],
        'subagency_slug': value['subagencySlug'],
        'agency_id': value['agencyId'],
        'agency_abbreviation': value['agencyAbbreviation'],
        'agency_name': value['agencyName'],
        'agency_slug': value['agencySlug'],
        'total_outlays': value['totalOutlays'],
    };
}

