/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner } from './ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner';
import {
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSONTyped,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSONTyped,
} from './ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner';

/**
 * 
 * @export
 * @interface ApiV2BulkDownloadListAgenciesPost200ResponseAgencies
 */
export interface ApiV2BulkDownloadListAgenciesPost200ResponseAgencies {
    /**
     * 
     * @type {Array<ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner>}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseAgencies
     */
    cfoAgencies: Array<ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner>;
    /**
     * 
     * @type {Array<ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner>}
     * @memberof ApiV2BulkDownloadListAgenciesPost200ResponseAgencies
     */
    otherAgencies: Array<ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInner>;
}

/**
 * Check if a given object implements the ApiV2BulkDownloadListAgenciesPost200ResponseAgencies interface.
 */
export function instanceOfApiV2BulkDownloadListAgenciesPost200ResponseAgencies(value: object): value is ApiV2BulkDownloadListAgenciesPost200ResponseAgencies {
    if (!('cfoAgencies' in value) || value['cfoAgencies'] === undefined) return false;
    if (!('otherAgencies' in value) || value['otherAgencies'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseAgencies {
    return ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadListAgenciesPost200ResponseAgencies {
    if (json == null) {
        return json;
    }
    return {
        
        'cfoAgencies': ((json['cfo_agencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSON)),
        'otherAgencies': ((json['other_agencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerFromJSON)),
    };
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSON(json: any): ApiV2BulkDownloadListAgenciesPost200ResponseAgencies {
    return ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSONTyped(value?: ApiV2BulkDownloadListAgenciesPost200ResponseAgencies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cfo_agencies': ((value['cfoAgencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSON)),
        'other_agencies': ((value['otherAgencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesCfoAgenciesInnerToJSON)),
    };
}

