/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency } from './ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency';
import {
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency';
import type { ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgency } from './ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgency';
import {
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyFromJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyToJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgency';

/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200ResponseAwardingAgency
 */
export interface ApiV2AwardsAwardIdPost200ResponseAwardingAgency {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgency
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgency
     */
    hasAgencyPage: boolean;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgency
     */
    toptierAgency: ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency | null;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgency}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgency
     */
    subtierAgency: ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgency | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgency
     */
    officeAgencyName: string | null;
}

/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200ResponseAwardingAgency interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200ResponseAwardingAgency(value: object): value is ApiV2AwardsAwardIdPost200ResponseAwardingAgency {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hasAgencyPage' in value) || value['hasAgencyPage'] === undefined) return false;
    if (!('toptierAgency' in value) || value['toptierAgency'] === undefined) return false;
    if (!('subtierAgency' in value) || value['subtierAgency'] === undefined) return false;
    if (!('officeAgencyName' in value) || value['officeAgencyName'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSON(json: any): ApiV2AwardsAwardIdPost200ResponseAwardingAgency {
    return ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200ResponseAwardingAgency {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hasAgencyPage': json['has_agency_page'],
        'toptierAgency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSON(json['toptier_agency']),
        'subtierAgency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyFromJSON(json['subtier_agency']),
        'officeAgencyName': json['office_agency_name'],
    };
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSON(json: any): ApiV2AwardsAwardIdPost200ResponseAwardingAgency {
    return ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSONTyped(value?: ApiV2AwardsAwardIdPost200ResponseAwardingAgency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'has_agency_page': value['hasAgencyPage'],
        'toptier_agency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSON(value['toptierAgency']),
        'subtier_agency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencySubtierAgencyToJSON(value['subtierAgency']),
        'office_agency_name': value['officeAgencyName'],
    };
}

