/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2SearchSpendingOverTimePost200ResponseResultsInner } from './ApiV2SearchSpendingOverTimePost200ResponseResultsInner';
import {
    ApiV2SearchSpendingOverTimePost200ResponseResultsInnerFromJSON,
    ApiV2SearchSpendingOverTimePost200ResponseResultsInnerFromJSONTyped,
    ApiV2SearchSpendingOverTimePost200ResponseResultsInnerToJSON,
    ApiV2SearchSpendingOverTimePost200ResponseResultsInnerToJSONTyped,
} from './ApiV2SearchSpendingOverTimePost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2SearchSpendingOverTimePost200Response
 */
export interface ApiV2SearchSpendingOverTimePost200Response {
    /**
     * 
     * @type {ApiV2SearchSpendingOverTimePost200ResponseGroupEnum}
     * @memberof ApiV2SearchSpendingOverTimePost200Response
     */
    group: ApiV2SearchSpendingOverTimePost200ResponseGroupEnum;
    /**
     * Spending level value that was provided in the request.
     * @type {ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum}
     * @memberof ApiV2SearchSpendingOverTimePost200Response
     */
    spendingLevel: ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum;
    /**
     * 
     * @type {Array<ApiV2SearchSpendingOverTimePost200ResponseResultsInner>}
     * @memberof ApiV2SearchSpendingOverTimePost200Response
     */
    results?: Array<ApiV2SearchSpendingOverTimePost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string | null>}
     * @memberof ApiV2SearchSpendingOverTimePost200Response
     */
    messages?: Array<string | null>;
}


/**
 * @export
 */
export const ApiV2SearchSpendingOverTimePost200ResponseGroupEnum = {
    CalendarYear: 'calendar_year',
    FiscalYear: 'fiscal_year',
    Quarter: 'quarter',
    Month: 'month'
} as const;
export type ApiV2SearchSpendingOverTimePost200ResponseGroupEnum = typeof ApiV2SearchSpendingOverTimePost200ResponseGroupEnum[keyof typeof ApiV2SearchSpendingOverTimePost200ResponseGroupEnum];

/**
 * @export
 */
export const ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum = {
    Transactions: 'transactions',
    Awards: 'awards',
    Subawards: 'subawards'
} as const;
export type ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum = typeof ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum[keyof typeof ApiV2SearchSpendingOverTimePost200ResponseSpendingLevelEnum];


/**
 * Check if a given object implements the ApiV2SearchSpendingOverTimePost200Response interface.
 */
export function instanceOfApiV2SearchSpendingOverTimePost200Response(value: object): value is ApiV2SearchSpendingOverTimePost200Response {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('spendingLevel' in value) || value['spendingLevel'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingOverTimePost200ResponseFromJSON(json: any): ApiV2SearchSpendingOverTimePost200Response {
    return ApiV2SearchSpendingOverTimePost200ResponseFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingOverTimePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingOverTimePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'],
        'spendingLevel': json['spending_level'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ApiV2SearchSpendingOverTimePost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ApiV2SearchSpendingOverTimePost200ResponseToJSON(json: any): ApiV2SearchSpendingOverTimePost200Response {
    return ApiV2SearchSpendingOverTimePost200ResponseToJSONTyped(json, false);
}

export function ApiV2SearchSpendingOverTimePost200ResponseToJSONTyped(value?: ApiV2SearchSpendingOverTimePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'spending_level': value['spendingLevel'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ApiV2SearchSpendingOverTimePost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

