/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
 */
export interface ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    clingerCohenActPlanning: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    clingerCohenActPlanningDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    commercialItemAcquisition: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    commercialItemAcquisitionDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    commercialItemTestProgram: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    commercialItemTestProgramDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    consolidatedContract: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    consolidatedContractDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    constructionWageRate: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    constructionWageRateDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    costOrPricingData: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    costOrPricingDataDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    dodAcquisitionProgram: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    dodAcquisitionProgramDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    dodClaimantProgram: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    dodClaimantProgramDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    domesticOrForeignEntity: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    domesticOrForeignEntityDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    evaluatedPreference: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    evaluatedPreferenceDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    extentCompeted: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    extentCompetedDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    fairOpportunityLimited: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    fairOpportunityLimitedDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    fedBizOpps: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    fedBizOppsDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    foreignFunding: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    foreignFundingDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    idvTypeDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    informationTechnologyCommercialItemCategory: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    informationTechnologyCommercialItemCategoryDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    interagencyContractingAuthority: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    interagencyContractingAuthorityDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    laborStandards: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    laborStandardsDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    majorProgram: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    materialsSupplies: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    materialsSuppliesDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    multiYearContract: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    multiYearContractDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    multipleOrSingleAwardDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    naics: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    naicsDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    nationalInterestAction: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    nationalInterestActionDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    numberOfOffersReceived: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    otherThanFullAndOpen: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    otherThanFullAndOpenDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    priceEvaluationAdjustment: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    productOrServiceCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    productOrServiceDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    programAcronym: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    purchaseCardAsPaymentMethod: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    purchaseCardAsPaymentMethodDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    referencedIdvAgencyIden: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    referencedIdvAgencyDesc: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    seaTransportation: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    seaTransportationDescription: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    smallBusinessCompetitive: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    solicitationIdentifier: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    solicitationProcedures: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    solicitationProceduresDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    subcontractingPlan: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    subcontractingPlanDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    typeOfContractPricing: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    typeOfContractPricingDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    typeOfIdcDescription: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    typeSetAside: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData
     */
    typeSetAsideDescription: string | null;
}

/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData(value: object): value is ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData {
    if (!('clingerCohenActPlanning' in value) || value['clingerCohenActPlanning'] === undefined) return false;
    if (!('clingerCohenActPlanningDescription' in value) || value['clingerCohenActPlanningDescription'] === undefined) return false;
    if (!('commercialItemAcquisition' in value) || value['commercialItemAcquisition'] === undefined) return false;
    if (!('commercialItemAcquisitionDescription' in value) || value['commercialItemAcquisitionDescription'] === undefined) return false;
    if (!('commercialItemTestProgram' in value) || value['commercialItemTestProgram'] === undefined) return false;
    if (!('commercialItemTestProgramDescription' in value) || value['commercialItemTestProgramDescription'] === undefined) return false;
    if (!('consolidatedContract' in value) || value['consolidatedContract'] === undefined) return false;
    if (!('consolidatedContractDescription' in value) || value['consolidatedContractDescription'] === undefined) return false;
    if (!('constructionWageRate' in value) || value['constructionWageRate'] === undefined) return false;
    if (!('constructionWageRateDescription' in value) || value['constructionWageRateDescription'] === undefined) return false;
    if (!('costOrPricingData' in value) || value['costOrPricingData'] === undefined) return false;
    if (!('costOrPricingDataDescription' in value) || value['costOrPricingDataDescription'] === undefined) return false;
    if (!('dodAcquisitionProgram' in value) || value['dodAcquisitionProgram'] === undefined) return false;
    if (!('dodAcquisitionProgramDescription' in value) || value['dodAcquisitionProgramDescription'] === undefined) return false;
    if (!('dodClaimantProgram' in value) || value['dodClaimantProgram'] === undefined) return false;
    if (!('dodClaimantProgramDescription' in value) || value['dodClaimantProgramDescription'] === undefined) return false;
    if (!('domesticOrForeignEntity' in value) || value['domesticOrForeignEntity'] === undefined) return false;
    if (!('domesticOrForeignEntityDescription' in value) || value['domesticOrForeignEntityDescription'] === undefined) return false;
    if (!('evaluatedPreference' in value) || value['evaluatedPreference'] === undefined) return false;
    if (!('evaluatedPreferenceDescription' in value) || value['evaluatedPreferenceDescription'] === undefined) return false;
    if (!('extentCompeted' in value) || value['extentCompeted'] === undefined) return false;
    if (!('extentCompetedDescription' in value) || value['extentCompetedDescription'] === undefined) return false;
    if (!('fairOpportunityLimited' in value) || value['fairOpportunityLimited'] === undefined) return false;
    if (!('fairOpportunityLimitedDescription' in value) || value['fairOpportunityLimitedDescription'] === undefined) return false;
    if (!('fedBizOpps' in value) || value['fedBizOpps'] === undefined) return false;
    if (!('fedBizOppsDescription' in value) || value['fedBizOppsDescription'] === undefined) return false;
    if (!('foreignFunding' in value) || value['foreignFunding'] === undefined) return false;
    if (!('foreignFundingDescription' in value) || value['foreignFundingDescription'] === undefined) return false;
    if (!('idvTypeDescription' in value) || value['idvTypeDescription'] === undefined) return false;
    if (!('informationTechnologyCommercialItemCategory' in value) || value['informationTechnologyCommercialItemCategory'] === undefined) return false;
    if (!('informationTechnologyCommercialItemCategoryDescription' in value) || value['informationTechnologyCommercialItemCategoryDescription'] === undefined) return false;
    if (!('interagencyContractingAuthority' in value) || value['interagencyContractingAuthority'] === undefined) return false;
    if (!('interagencyContractingAuthorityDescription' in value) || value['interagencyContractingAuthorityDescription'] === undefined) return false;
    if (!('laborStandards' in value) || value['laborStandards'] === undefined) return false;
    if (!('laborStandardsDescription' in value) || value['laborStandardsDescription'] === undefined) return false;
    if (!('majorProgram' in value) || value['majorProgram'] === undefined) return false;
    if (!('materialsSupplies' in value) || value['materialsSupplies'] === undefined) return false;
    if (!('materialsSuppliesDescription' in value) || value['materialsSuppliesDescription'] === undefined) return false;
    if (!('multiYearContract' in value) || value['multiYearContract'] === undefined) return false;
    if (!('multiYearContractDescription' in value) || value['multiYearContractDescription'] === undefined) return false;
    if (!('multipleOrSingleAwardDescription' in value) || value['multipleOrSingleAwardDescription'] === undefined) return false;
    if (!('naics' in value) || value['naics'] === undefined) return false;
    if (!('naicsDescription' in value) || value['naicsDescription'] === undefined) return false;
    if (!('nationalInterestAction' in value) || value['nationalInterestAction'] === undefined) return false;
    if (!('nationalInterestActionDescription' in value) || value['nationalInterestActionDescription'] === undefined) return false;
    if (!('numberOfOffersReceived' in value) || value['numberOfOffersReceived'] === undefined) return false;
    if (!('otherThanFullAndOpen' in value) || value['otherThanFullAndOpen'] === undefined) return false;
    if (!('otherThanFullAndOpenDescription' in value) || value['otherThanFullAndOpenDescription'] === undefined) return false;
    if (!('priceEvaluationAdjustment' in value) || value['priceEvaluationAdjustment'] === undefined) return false;
    if (!('productOrServiceCode' in value) || value['productOrServiceCode'] === undefined) return false;
    if (!('productOrServiceDescription' in value) || value['productOrServiceDescription'] === undefined) return false;
    if (!('programAcronym' in value) || value['programAcronym'] === undefined) return false;
    if (!('purchaseCardAsPaymentMethod' in value) || value['purchaseCardAsPaymentMethod'] === undefined) return false;
    if (!('purchaseCardAsPaymentMethodDescription' in value) || value['purchaseCardAsPaymentMethodDescription'] === undefined) return false;
    if (!('referencedIdvAgencyIden' in value) || value['referencedIdvAgencyIden'] === undefined) return false;
    if (!('referencedIdvAgencyDesc' in value) || value['referencedIdvAgencyDesc'] === undefined) return false;
    if (!('seaTransportation' in value) || value['seaTransportation'] === undefined) return false;
    if (!('seaTransportationDescription' in value) || value['seaTransportationDescription'] === undefined) return false;
    if (!('smallBusinessCompetitive' in value) || value['smallBusinessCompetitive'] === undefined) return false;
    if (!('solicitationIdentifier' in value) || value['solicitationIdentifier'] === undefined) return false;
    if (!('solicitationProcedures' in value) || value['solicitationProcedures'] === undefined) return false;
    if (!('solicitationProceduresDescription' in value) || value['solicitationProceduresDescription'] === undefined) return false;
    if (!('subcontractingPlan' in value) || value['subcontractingPlan'] === undefined) return false;
    if (!('subcontractingPlanDescription' in value) || value['subcontractingPlanDescription'] === undefined) return false;
    if (!('typeOfContractPricing' in value) || value['typeOfContractPricing'] === undefined) return false;
    if (!('typeOfContractPricingDescription' in value) || value['typeOfContractPricingDescription'] === undefined) return false;
    if (!('typeOfIdcDescription' in value) || value['typeOfIdcDescription'] === undefined) return false;
    if (!('typeSetAside' in value) || value['typeSetAside'] === undefined) return false;
    if (!('typeSetAsideDescription' in value) || value['typeSetAsideDescription'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSON(json: any): ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData {
    return ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData {
    if (json == null) {
        return json;
    }
    return {
        
        'clingerCohenActPlanning': json['clinger_cohen_act_planning'],
        'clingerCohenActPlanningDescription': json['clinger_cohen_act_planning_description'],
        'commercialItemAcquisition': json['commercial_item_acquisition'],
        'commercialItemAcquisitionDescription': json['commercial_item_acquisition_description'],
        'commercialItemTestProgram': json['commercial_item_test_program'],
        'commercialItemTestProgramDescription': json['commercial_item_test_program_description'],
        'consolidatedContract': json['consolidated_contract'],
        'consolidatedContractDescription': json['consolidated_contract_description'],
        'constructionWageRate': json['construction_wage_rate'],
        'constructionWageRateDescription': json['construction_wage_rate_description'],
        'costOrPricingData': json['cost_or_pricing_data'],
        'costOrPricingDataDescription': json['cost_or_pricing_data_description'],
        'dodAcquisitionProgram': json['dod_acquisition_program'],
        'dodAcquisitionProgramDescription': json['dod_acquisition_program_description'],
        'dodClaimantProgram': json['dod_claimant_program'],
        'dodClaimantProgramDescription': json['dod_claimant_program_description'],
        'domesticOrForeignEntity': json['domestic_or_foreign_entity'],
        'domesticOrForeignEntityDescription': json['domestic_or_foreign_entity_description'],
        'evaluatedPreference': json['evaluated_preference'],
        'evaluatedPreferenceDescription': json['evaluated_preference_description'],
        'extentCompeted': json['extent_competed'],
        'extentCompetedDescription': json['extent_competed_description'],
        'fairOpportunityLimited': json['fair_opportunity_limited'],
        'fairOpportunityLimitedDescription': json['fair_opportunity_limited_description'],
        'fedBizOpps': json['fed_biz_opps'],
        'fedBizOppsDescription': json['fed_biz_opps_description'],
        'foreignFunding': json['foreign_funding'],
        'foreignFundingDescription': json['foreign_funding_description'],
        'idvTypeDescription': json['idv_type_description'],
        'informationTechnologyCommercialItemCategory': json['information_technology_commercial_item_category'],
        'informationTechnologyCommercialItemCategoryDescription': json['information_technology_commercial_item_category_description'],
        'interagencyContractingAuthority': json['interagency_contracting_authority'],
        'interagencyContractingAuthorityDescription': json['interagency_contracting_authority_description'],
        'laborStandards': json['labor_standards'],
        'laborStandardsDescription': json['labor_standards_description'],
        'majorProgram': json['major_program'],
        'materialsSupplies': json['materials_supplies'],
        'materialsSuppliesDescription': json['materials_supplies_description'],
        'multiYearContract': json['multi_year_contract'],
        'multiYearContractDescription': json['multi_year_contract_description'],
        'multipleOrSingleAwardDescription': json['multiple_or_single_award_description'],
        'naics': json['naics'],
        'naicsDescription': json['naics_description'],
        'nationalInterestAction': json['national_interest_action'],
        'nationalInterestActionDescription': json['national_interest_action_description'],
        'numberOfOffersReceived': json['number_of_offers_received'],
        'otherThanFullAndOpen': json['other_than_full_and_open'],
        'otherThanFullAndOpenDescription': json['other_than_full_and_open_description'],
        'priceEvaluationAdjustment': json['price_evaluation_adjustment'],
        'productOrServiceCode': json['product_or_service_code'],
        'productOrServiceDescription': json['product_or_service_description'],
        'programAcronym': json['program_acronym'],
        'purchaseCardAsPaymentMethod': json['purchase_card_as_payment_method'],
        'purchaseCardAsPaymentMethodDescription': json['purchase_card_as_payment_method_description'],
        'referencedIdvAgencyIden': json['referenced_idv_agency_iden'],
        'referencedIdvAgencyDesc': json['referenced_idv_agency_desc'],
        'seaTransportation': json['sea_transportation'],
        'seaTransportationDescription': json['sea_transportation_description'],
        'smallBusinessCompetitive': json['small_business_competitive'],
        'solicitationIdentifier': json['solicitation_identifier'],
        'solicitationProcedures': json['solicitation_procedures'],
        'solicitationProceduresDescription': json['solicitation_procedures_description'],
        'subcontractingPlan': json['subcontracting_plan'],
        'subcontractingPlanDescription': json['subcontracting_plan_description'],
        'typeOfContractPricing': json['type_of_contract_pricing'],
        'typeOfContractPricingDescription': json['type_of_contract_pricing_description'],
        'typeOfIdcDescription': json['type_of_idc_description'],
        'typeSetAside': json['type_set_aside'],
        'typeSetAsideDescription': json['type_set_aside_description'],
    };
}

export function ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSON(json: any): ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData {
    return ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSONTyped(value?: ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clinger_cohen_act_planning': value['clingerCohenActPlanning'],
        'clinger_cohen_act_planning_description': value['clingerCohenActPlanningDescription'],
        'commercial_item_acquisition': value['commercialItemAcquisition'],
        'commercial_item_acquisition_description': value['commercialItemAcquisitionDescription'],
        'commercial_item_test_program': value['commercialItemTestProgram'],
        'commercial_item_test_program_description': value['commercialItemTestProgramDescription'],
        'consolidated_contract': value['consolidatedContract'],
        'consolidated_contract_description': value['consolidatedContractDescription'],
        'construction_wage_rate': value['constructionWageRate'],
        'construction_wage_rate_description': value['constructionWageRateDescription'],
        'cost_or_pricing_data': value['costOrPricingData'],
        'cost_or_pricing_data_description': value['costOrPricingDataDescription'],
        'dod_acquisition_program': value['dodAcquisitionProgram'],
        'dod_acquisition_program_description': value['dodAcquisitionProgramDescription'],
        'dod_claimant_program': value['dodClaimantProgram'],
        'dod_claimant_program_description': value['dodClaimantProgramDescription'],
        'domestic_or_foreign_entity': value['domesticOrForeignEntity'],
        'domestic_or_foreign_entity_description': value['domesticOrForeignEntityDescription'],
        'evaluated_preference': value['evaluatedPreference'],
        'evaluated_preference_description': value['evaluatedPreferenceDescription'],
        'extent_competed': value['extentCompeted'],
        'extent_competed_description': value['extentCompetedDescription'],
        'fair_opportunity_limited': value['fairOpportunityLimited'],
        'fair_opportunity_limited_description': value['fairOpportunityLimitedDescription'],
        'fed_biz_opps': value['fedBizOpps'],
        'fed_biz_opps_description': value['fedBizOppsDescription'],
        'foreign_funding': value['foreignFunding'],
        'foreign_funding_description': value['foreignFundingDescription'],
        'idv_type_description': value['idvTypeDescription'],
        'information_technology_commercial_item_category': value['informationTechnologyCommercialItemCategory'],
        'information_technology_commercial_item_category_description': value['informationTechnologyCommercialItemCategoryDescription'],
        'interagency_contracting_authority': value['interagencyContractingAuthority'],
        'interagency_contracting_authority_description': value['interagencyContractingAuthorityDescription'],
        'labor_standards': value['laborStandards'],
        'labor_standards_description': value['laborStandardsDescription'],
        'major_program': value['majorProgram'],
        'materials_supplies': value['materialsSupplies'],
        'materials_supplies_description': value['materialsSuppliesDescription'],
        'multi_year_contract': value['multiYearContract'],
        'multi_year_contract_description': value['multiYearContractDescription'],
        'multiple_or_single_award_description': value['multipleOrSingleAwardDescription'],
        'naics': value['naics'],
        'naics_description': value['naicsDescription'],
        'national_interest_action': value['nationalInterestAction'],
        'national_interest_action_description': value['nationalInterestActionDescription'],
        'number_of_offers_received': value['numberOfOffersReceived'],
        'other_than_full_and_open': value['otherThanFullAndOpen'],
        'other_than_full_and_open_description': value['otherThanFullAndOpenDescription'],
        'price_evaluation_adjustment': value['priceEvaluationAdjustment'],
        'product_or_service_code': value['productOrServiceCode'],
        'product_or_service_description': value['productOrServiceDescription'],
        'program_acronym': value['programAcronym'],
        'purchase_card_as_payment_method': value['purchaseCardAsPaymentMethod'],
        'purchase_card_as_payment_method_description': value['purchaseCardAsPaymentMethodDescription'],
        'referenced_idv_agency_iden': value['referencedIdvAgencyIden'],
        'referenced_idv_agency_desc': value['referencedIdvAgencyDesc'],
        'sea_transportation': value['seaTransportation'],
        'sea_transportation_description': value['seaTransportationDescription'],
        'small_business_competitive': value['smallBusinessCompetitive'],
        'solicitation_identifier': value['solicitationIdentifier'],
        'solicitation_procedures': value['solicitationProcedures'],
        'solicitation_procedures_description': value['solicitationProceduresDescription'],
        'subcontracting_plan': value['subcontractingPlan'],
        'subcontracting_plan_description': value['subcontractingPlanDescription'],
        'type_of_contract_pricing': value['typeOfContractPricing'],
        'type_of_contract_pricing_description': value['typeOfContractPricingDescription'],
        'type_of_idc_description': value['typeOfIdcDescription'],
        'type_set_aside': value['typeSetAside'],
        'type_set_aside_description': value['typeSetAsideDescription'],
    };
}

