/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AgencyToptierCodePost200ResponseDefCodesInner } from './ApiV2AgencyToptierCodePost200ResponseDefCodesInner';
import {
    ApiV2AgencyToptierCodePost200ResponseDefCodesInnerFromJSON,
    ApiV2AgencyToptierCodePost200ResponseDefCodesInnerFromJSONTyped,
    ApiV2AgencyToptierCodePost200ResponseDefCodesInnerToJSON,
    ApiV2AgencyToptierCodePost200ResponseDefCodesInnerToJSONTyped,
} from './ApiV2AgencyToptierCodePost200ResponseDefCodesInner';

/**
 * 
 * @export
 * @interface ApiV2AgencyToptierCodePost200Response
 */
export interface ApiV2AgencyToptierCodePost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    toptierCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    abbreviation: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    agencyId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    iconFilename: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    mission: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    website: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    congressionalJustificationUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    aboutAgencyData: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    subtierAgencyCount: number;
    /**
     * 
     * @type {Array<ApiV2AgencyToptierCodePost200ResponseDefCodesInner>}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    defCodes: Array<ApiV2AgencyToptierCodePost200ResponseDefCodesInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyToptierCodePost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyToptierCodePost200Response interface.
 */
export function instanceOfApiV2AgencyToptierCodePost200Response(value: object): value is ApiV2AgencyToptierCodePost200Response {
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('agencyId' in value) || value['agencyId'] === undefined) return false;
    if (!('iconFilename' in value) || value['iconFilename'] === undefined) return false;
    if (!('mission' in value) || value['mission'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('congressionalJustificationUrl' in value) || value['congressionalJustificationUrl'] === undefined) return false;
    if (!('aboutAgencyData' in value) || value['aboutAgencyData'] === undefined) return false;
    if (!('subtierAgencyCount' in value) || value['subtierAgencyCount'] === undefined) return false;
    if (!('defCodes' in value) || value['defCodes'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyToptierCodePost200ResponseFromJSON(json: any): ApiV2AgencyToptierCodePost200Response {
    return ApiV2AgencyToptierCodePost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyToptierCodePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'fiscalYear': json['fiscal_year'],
        'toptierCode': json['toptier_code'],
        'name': json['name'],
        'abbreviation': json['abbreviation'],
        'agencyId': json['agency_id'],
        'iconFilename': json['icon_filename'],
        'mission': json['mission'],
        'website': json['website'],
        'congressionalJustificationUrl': json['congressional_justification_url'],
        'aboutAgencyData': json['about_agency_data'],
        'subtierAgencyCount': json['subtier_agency_count'],
        'defCodes': ((json['def_codes'] as Array<any>).map(ApiV2AgencyToptierCodePost200ResponseDefCodesInnerFromJSON)),
        'messages': json['messages'],
    };
}

export function ApiV2AgencyToptierCodePost200ResponseToJSON(json: any): ApiV2AgencyToptierCodePost200Response {
    return ApiV2AgencyToptierCodePost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodePost200ResponseToJSONTyped(value?: ApiV2AgencyToptierCodePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fiscal_year': value['fiscalYear'],
        'toptier_code': value['toptierCode'],
        'name': value['name'],
        'abbreviation': value['abbreviation'],
        'agency_id': value['agencyId'],
        'icon_filename': value['iconFilename'],
        'mission': value['mission'],
        'website': value['website'],
        'congressional_justification_url': value['congressionalJustificationUrl'],
        'about_agency_data': value['aboutAgencyData'],
        'subtier_agency_count': value['subtierAgencyCount'],
        'def_codes': ((value['defCodes'] as Array<any>).map(ApiV2AgencyToptierCodePost200ResponseDefCodesInnerToJSON)),
        'messages': value['messages'],
    };
}

