/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner
 */
export interface ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner
     */
    count?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner
     */
    children?: Array<object>;
}

/**
 * Check if a given object implements the ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner(value: object): value is ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner {
    return ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
        'count': json['count'] == null ? undefined : json['count'],
        'children': json['children'] == null ? undefined : json['children'],
    };
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSON(json: any): ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner {
    return ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReferencesAssistanceListingCodeFilterPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
        'count': value['count'],
        'children': value['children'],
    };
}

