/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterAgencyLoansPost200ResponsePageMetadata } from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import {
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import type { ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInner } from './ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInner';
import {
    ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerFromJSON,
    ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerFromJSONTyped,
    ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerToJSON,
    ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesPublishDatesPost200Response
 */
export interface ApiV2ReportingAgenciesPublishDatesPost200Response {
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponsePageMetadata}
     * @memberof ApiV2ReportingAgenciesPublishDatesPost200Response
     */
    pageMetadata: ApiV2DisasterAgencyLoansPost200ResponsePageMetadata;
    /**
     * 
     * @type {Array<ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInner>}
     * @memberof ApiV2ReportingAgenciesPublishDatesPost200Response
     */
    results: Array<ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesPublishDatesPost200Response interface.
 */
export function instanceOfApiV2ReportingAgenciesPublishDatesPost200Response(value: object): value is ApiV2ReportingAgenciesPublishDatesPost200Response {
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesPublishDatesPost200ResponseFromJSON(json: any): ApiV2ReportingAgenciesPublishDatesPost200Response {
    return ApiV2ReportingAgenciesPublishDatesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesPublishDatesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesPublishDatesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageMetadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'results': ((json['results'] as Array<any>).map(ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2ReportingAgenciesPublishDatesPost200ResponseToJSON(json: any): ApiV2ReportingAgenciesPublishDatesPost200Response {
    return ApiV2ReportingAgenciesPublishDatesPost200ResponseToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesPublishDatesPost200ResponseToJSONTyped(value?: ApiV2ReportingAgenciesPublishDatesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_metadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'results': ((value['results'] as Array<any>).map(ApiV2ReportingAgenciesPublishDatesPost200ResponseResultsInnerToJSON)),
    };
}

