/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterAgencyLoansPost200ResponsePageMetadata } from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import {
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import type { ApiV2DisasterObjectClassSpendingPost200ResponseTotals } from './ApiV2DisasterObjectClassSpendingPost200ResponseTotals';
import {
    ApiV2DisasterObjectClassSpendingPost200ResponseTotalsFromJSON,
    ApiV2DisasterObjectClassSpendingPost200ResponseTotalsFromJSONTyped,
    ApiV2DisasterObjectClassSpendingPost200ResponseTotalsToJSON,
    ApiV2DisasterObjectClassSpendingPost200ResponseTotalsToJSONTyped,
} from './ApiV2DisasterObjectClassSpendingPost200ResponseTotals';
import type { ApiV2DisasterObjectClassSpendingPost200ResponseResultsInner } from './ApiV2DisasterObjectClassSpendingPost200ResponseResultsInner';
import {
    ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerFromJSON,
    ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerFromJSONTyped,
    ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerToJSON,
    ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2DisasterObjectClassSpendingPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2DisasterObjectClassSpendingPost200Response
 */
export interface ApiV2DisasterObjectClassSpendingPost200Response {
    /**
     * 
     * @type {ApiV2DisasterObjectClassSpendingPost200ResponseTotals}
     * @memberof ApiV2DisasterObjectClassSpendingPost200Response
     */
    totals: ApiV2DisasterObjectClassSpendingPost200ResponseTotals;
    /**
     * 
     * @type {Array<ApiV2DisasterObjectClassSpendingPost200ResponseResultsInner>}
     * @memberof ApiV2DisasterObjectClassSpendingPost200Response
     */
    results: Array<ApiV2DisasterObjectClassSpendingPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponsePageMetadata}
     * @memberof ApiV2DisasterObjectClassSpendingPost200Response
     */
    pageMetadata: ApiV2DisasterAgencyLoansPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2DisasterObjectClassSpendingPost200Response interface.
 */
export function instanceOfApiV2DisasterObjectClassSpendingPost200Response(value: object): value is ApiV2DisasterObjectClassSpendingPost200Response {
    if (!('totals' in value) || value['totals'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2DisasterObjectClassSpendingPost200ResponseFromJSON(json: any): ApiV2DisasterObjectClassSpendingPost200Response {
    return ApiV2DisasterObjectClassSpendingPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2DisasterObjectClassSpendingPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterObjectClassSpendingPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totals': ApiV2DisasterObjectClassSpendingPost200ResponseTotalsFromJSON(json['totals']),
        'results': ((json['results'] as Array<any>).map(ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2DisasterObjectClassSpendingPost200ResponseToJSON(json: any): ApiV2DisasterObjectClassSpendingPost200Response {
    return ApiV2DisasterObjectClassSpendingPost200ResponseToJSONTyped(json, false);
}

export function ApiV2DisasterObjectClassSpendingPost200ResponseToJSONTyped(value?: ApiV2DisasterObjectClassSpendingPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totals': ApiV2DisasterObjectClassSpendingPost200ResponseTotalsToJSON(value['totals']),
        'results': ((value['results'] as Array<any>).map(ApiV2DisasterObjectClassSpendingPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

