/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AgencyToptierCodeFederalAccountCountPost200Response
 */
export interface ApiV2AgencyToptierCodeFederalAccountCountPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodeFederalAccountCountPost200Response
     */
    toptierCode: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountCountPost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountCountPost200Response
     */
    federalAccountCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountCountPost200Response
     */
    treasuryAccountCount: number;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyToptierCodeFederalAccountCountPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyToptierCodeFederalAccountCountPost200Response interface.
 */
export function instanceOfApiV2AgencyToptierCodeFederalAccountCountPost200Response(value: object): value is ApiV2AgencyToptierCodeFederalAccountCountPost200Response {
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('federalAccountCount' in value) || value['federalAccountCount'] === undefined) return false;
    if (!('treasuryAccountCount' in value) || value['treasuryAccountCount'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseFromJSON(json: any): ApiV2AgencyToptierCodeFederalAccountCountPost200Response {
    return ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyToptierCodeFederalAccountCountPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'toptierCode': json['toptier_code'],
        'fiscalYear': json['fiscal_year'],
        'federalAccountCount': json['federal_account_count'],
        'treasuryAccountCount': json['treasury_account_count'],
        'messages': json['messages'],
    };
}

export function ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseToJSON(json: any): ApiV2AgencyToptierCodeFederalAccountCountPost200Response {
    return ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeFederalAccountCountPost200ResponseToJSONTyped(value?: ApiV2AgencyToptierCodeFederalAccountCountPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toptier_code': value['toptierCode'],
        'fiscal_year': value['fiscalYear'],
        'federal_account_count': value['federalAccountCount'],
        'treasury_account_count': value['treasuryAccountCount'],
        'messages': value['messages'],
    };
}

