/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AwardsAwardIdPost200ResponseExecutiveDetails } from './ApiV2AwardsAwardIdPost200ResponseExecutiveDetails';
import {
    ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsFromJSON,
    ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsToJSON,
    ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseExecutiveDetails';
import type { ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner } from './ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner';
import {
    ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerFromJSON,
    ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerToJSON,
    ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner';
import type { ApiV2AwardsAwardIdPost200ResponseFundingAgency } from './ApiV2AwardsAwardIdPost200ResponseFundingAgency';
import {
    ApiV2AwardsAwardIdPost200ResponseFundingAgencyFromJSON,
    ApiV2AwardsAwardIdPost200ResponseFundingAgencyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseFundingAgencyToJSON,
    ApiV2AwardsAwardIdPost200ResponseFundingAgencyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseFundingAgency';
import type { ApiV2AwardsAwardIdPost200ResponseAwardingAgency } from './ApiV2AwardsAwardIdPost200ResponseAwardingAgency';
import {
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSON,
    ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseAwardingAgency';
import type { ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformance } from './ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformance';
import {
    ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceFromJSON,
    ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceToJSON,
    ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformance';
import type { ApiV2AwardsAwardIdPost200ResponsePscHierarchy } from './ApiV2AwardsAwardIdPost200ResponsePscHierarchy';
import {
    ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSON,
    ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSON,
    ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponsePscHierarchy';
import type { ApiV2AwardsAwardIdPost200ResponseNaicsHierarchy } from './ApiV2AwardsAwardIdPost200ResponseNaicsHierarchy';
import {
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyFromJSON,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToJSON,
    ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseNaicsHierarchy';
import type { ApiV2AwardsAwardIdPost200ResponseRecipient } from './ApiV2AwardsAwardIdPost200ResponseRecipient';
import {
    ApiV2AwardsAwardIdPost200ResponseRecipientFromJSON,
    ApiV2AwardsAwardIdPost200ResponseRecipientFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseRecipientToJSON,
    ApiV2AwardsAwardIdPost200ResponseRecipientToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseRecipient';
import type { ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformance } from './ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformance';
import {
    ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceFromJSON,
    ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceToJSON,
    ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformance';
import type { ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData } from './ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData';
import {
    ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSON,
    ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSON,
    ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData';
import type { ApiV2AwardsAwardIdPost200ResponseParentAward } from './ApiV2AwardsAwardIdPost200ResponseParentAward';
import {
    ApiV2AwardsAwardIdPost200ResponseParentAwardFromJSON,
    ApiV2AwardsAwardIdPost200ResponseParentAwardFromJSONTyped,
    ApiV2AwardsAwardIdPost200ResponseParentAwardToJSON,
    ApiV2AwardsAwardIdPost200ResponseParentAwardToJSONTyped,
} from './ApiV2AwardsAwardIdPost200ResponseParentAward';

/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200Response
 */
export interface ApiV2AwardsAwardIdPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    id: number;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseCategoryEnum}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    category: ApiV2AwardsAwardIdPost200ResponseCategoryEnum;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseTypeEnum}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    type: ApiV2AwardsAwardIdPost200ResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    typeDescription: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    generatedUniqueAwardId: string;
    /**
     * Award id
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    piid: string;
    /**
     * Description of the first transaction for this award
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    totalObligation: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    baseExercisedOptions: number | null;
    /**
     * The ceiling and amount of the award
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    baseAndAllOptions: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    dateSigned: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    subawardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    totalSubawardAmount: number | null;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseAwardingAgency}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    awardingAgency: ApiV2AwardsAwardIdPost200ResponseAwardingAgency;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseFundingAgency}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    fundingAgency: ApiV2AwardsAwardIdPost200ResponseFundingAgency | null;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseRecipient}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    recipient: ApiV2AwardsAwardIdPost200ResponseRecipient;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformance}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    periodOfPerformance: ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformance;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformance}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    placeOfPerformance: ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformance;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    latestTransactionContractData: ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractData;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseExecutiveDetails}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    executiveDetails: ApiV2AwardsAwardIdPost200ResponseExecutiveDetails;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseParentAward}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    parentAward: ApiV2AwardsAwardIdPost200ResponseParentAward | null;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponseNaicsHierarchy}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    naicsHierarchy: ApiV2AwardsAwardIdPost200ResponseNaicsHierarchy;
    /**
     * 
     * @type {ApiV2AwardsAwardIdPost200ResponsePscHierarchy}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    pscHierarchy: ApiV2AwardsAwardIdPost200ResponsePscHierarchy;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    totalAccountOutlay: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    totalAccountObligation: number;
    /**
     * 
     * @type {Array<ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner>}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    accountObligationsByDefc: Array<ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner>;
    /**
     * 
     * @type {Array<ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner>}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    accountOutlaysByDefc: Array<ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInner>;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200Response
     */
    totalOutlay: number | null;
}


/**
 * @export
 */
export const ApiV2AwardsAwardIdPost200ResponseCategoryEnum = {
    Idv: 'idv'
} as const;
export type ApiV2AwardsAwardIdPost200ResponseCategoryEnum = typeof ApiV2AwardsAwardIdPost200ResponseCategoryEnum[keyof typeof ApiV2AwardsAwardIdPost200ResponseCategoryEnum];

/**
 * @export
 */
export const ApiV2AwardsAwardIdPost200ResponseTypeEnum = {
    IdvA: 'IDV_A',
    IdvB: 'IDV_B',
    IdvBA: 'IDV_B_A',
    IdvBB: 'IDV_B_B',
    IdvBC: 'IDV_B_C',
    IdvC: 'IDV_C',
    IdvD: 'IDV_D',
    IdvE: 'IDV_E'
} as const;
export type ApiV2AwardsAwardIdPost200ResponseTypeEnum = typeof ApiV2AwardsAwardIdPost200ResponseTypeEnum[keyof typeof ApiV2AwardsAwardIdPost200ResponseTypeEnum];


/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200Response interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200Response(value: object): value is ApiV2AwardsAwardIdPost200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('typeDescription' in value) || value['typeDescription'] === undefined) return false;
    if (!('generatedUniqueAwardId' in value) || value['generatedUniqueAwardId'] === undefined) return false;
    if (!('piid' in value) || value['piid'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('totalObligation' in value) || value['totalObligation'] === undefined) return false;
    if (!('baseExercisedOptions' in value) || value['baseExercisedOptions'] === undefined) return false;
    if (!('baseAndAllOptions' in value) || value['baseAndAllOptions'] === undefined) return false;
    if (!('dateSigned' in value) || value['dateSigned'] === undefined) return false;
    if (!('subawardCount' in value) || value['subawardCount'] === undefined) return false;
    if (!('totalSubawardAmount' in value) || value['totalSubawardAmount'] === undefined) return false;
    if (!('awardingAgency' in value) || value['awardingAgency'] === undefined) return false;
    if (!('fundingAgency' in value) || value['fundingAgency'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('periodOfPerformance' in value) || value['periodOfPerformance'] === undefined) return false;
    if (!('placeOfPerformance' in value) || value['placeOfPerformance'] === undefined) return false;
    if (!('latestTransactionContractData' in value) || value['latestTransactionContractData'] === undefined) return false;
    if (!('executiveDetails' in value) || value['executiveDetails'] === undefined) return false;
    if (!('parentAward' in value) || value['parentAward'] === undefined) return false;
    if (!('naicsHierarchy' in value) || value['naicsHierarchy'] === undefined) return false;
    if (!('pscHierarchy' in value) || value['pscHierarchy'] === undefined) return false;
    if (!('totalAccountOutlay' in value) || value['totalAccountOutlay'] === undefined) return false;
    if (!('totalAccountObligation' in value) || value['totalAccountObligation'] === undefined) return false;
    if (!('accountObligationsByDefc' in value) || value['accountObligationsByDefc'] === undefined) return false;
    if (!('accountOutlaysByDefc' in value) || value['accountOutlaysByDefc'] === undefined) return false;
    if (!('totalOutlay' in value) || value['totalOutlay'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponseFromJSON(json: any): ApiV2AwardsAwardIdPost200Response {
    return ApiV2AwardsAwardIdPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'category': json['category'],
        'type': json['type'],
        'typeDescription': json['type_description'],
        'generatedUniqueAwardId': json['generated_unique_award_id'],
        'piid': json['piid'],
        'description': json['description'],
        'totalObligation': json['total_obligation'],
        'baseExercisedOptions': json['base_exercised_options'],
        'baseAndAllOptions': json['base_and_all_options'],
        'dateSigned': json['date_signed'],
        'subawardCount': json['subaward_count'],
        'totalSubawardAmount': json['total_subaward_amount'],
        'awardingAgency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencyFromJSON(json['awarding_agency']),
        'fundingAgency': ApiV2AwardsAwardIdPost200ResponseFundingAgencyFromJSON(json['funding_agency']),
        'recipient': ApiV2AwardsAwardIdPost200ResponseRecipientFromJSON(json['recipient']),
        'periodOfPerformance': ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceFromJSON(json['period_of_performance']),
        'placeOfPerformance': ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceFromJSON(json['place_of_performance']),
        'latestTransactionContractData': ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataFromJSON(json['latest_transaction_contract_data']),
        'executiveDetails': ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsFromJSON(json['executive_details']),
        'parentAward': ApiV2AwardsAwardIdPost200ResponseParentAwardFromJSON(json['parent_award']),
        'naicsHierarchy': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyFromJSON(json['naics_hierarchy']),
        'pscHierarchy': ApiV2AwardsAwardIdPost200ResponsePscHierarchyFromJSON(json['psc_hierarchy']),
        'totalAccountOutlay': json['total_account_outlay'],
        'totalAccountObligation': json['total_account_obligation'],
        'accountObligationsByDefc': ((json['account_obligations_by_defc'] as Array<any>).map(ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerFromJSON)),
        'accountOutlaysByDefc': ((json['account_outlays_by_defc'] as Array<any>).map(ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerFromJSON)),
        'totalOutlay': json['total_outlay'],
    };
}

export function ApiV2AwardsAwardIdPost200ResponseToJSON(json: any): ApiV2AwardsAwardIdPost200Response {
    return ApiV2AwardsAwardIdPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseToJSONTyped(value?: ApiV2AwardsAwardIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'type': value['type'],
        'type_description': value['typeDescription'],
        'generated_unique_award_id': value['generatedUniqueAwardId'],
        'piid': value['piid'],
        'description': value['description'],
        'total_obligation': value['totalObligation'],
        'base_exercised_options': value['baseExercisedOptions'],
        'base_and_all_options': value['baseAndAllOptions'],
        'date_signed': value['dateSigned'],
        'subaward_count': value['subawardCount'],
        'total_subaward_amount': value['totalSubawardAmount'],
        'awarding_agency': ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToJSON(value['awardingAgency']),
        'funding_agency': ApiV2AwardsAwardIdPost200ResponseFundingAgencyToJSON(value['fundingAgency']),
        'recipient': ApiV2AwardsAwardIdPost200ResponseRecipientToJSON(value['recipient']),
        'period_of_performance': ApiV2AwardsAwardIdPost200ResponsePeriodOfPerformanceToJSON(value['periodOfPerformance']),
        'place_of_performance': ApiV2AwardsAwardIdPost200ResponsePlaceOfPerformanceToJSON(value['placeOfPerformance']),
        'latest_transaction_contract_data': ApiV2AwardsAwardIdPost200ResponseLatestTransactionContractDataToJSON(value['latestTransactionContractData']),
        'executive_details': ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsToJSON(value['executiveDetails']),
        'parent_award': ApiV2AwardsAwardIdPost200ResponseParentAwardToJSON(value['parentAward']),
        'naics_hierarchy': ApiV2AwardsAwardIdPost200ResponseNaicsHierarchyToJSON(value['naicsHierarchy']),
        'psc_hierarchy': ApiV2AwardsAwardIdPost200ResponsePscHierarchyToJSON(value['pscHierarchy']),
        'total_account_outlay': value['totalAccountOutlay'],
        'total_account_obligation': value['totalAccountObligation'],
        'account_obligations_by_defc': ((value['accountObligationsByDefc'] as Array<any>).map(ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerToJSON)),
        'account_outlays_by_defc': ((value['accountOutlaysByDefc'] as Array<any>).map(ApiV2AwardsAwardIdPost200ResponseAccountObligationsByDefcInnerToJSON)),
        'total_outlay': value['totalOutlay'],
    };
}

