/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByAwardPost200ResponseResultsInner
 */
export interface ApiV2SearchSpendingByAwardPost200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    internalId: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    totalOutlays?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardID?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardingAgencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardingAgency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardingAgencyId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardingSubAgencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    awardingSubAgency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    baseObligationDate?: string;
    /**
     * Assistance awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    cFDANumber?: string | null;
    /**
     * Procurement awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    contractAwardType?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    fundingAgencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    fundingAgency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    fundingSubAgencyCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    fundingSubAgency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    generatedInternalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    issuedDate?: string | null;
    /**
     * Procurement IDVs only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    lastDateToOrder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    lastModifiedDate?: string;
    /**
     * Assistance awards only
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    loanValue?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    periodOfPerformanceCurrentEndDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    periodOfPerformanceStartDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    placeOfPerformanceCityCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    placeOfPerformanceCountryCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    placeOfPerformanceStateCode?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    placeOfPerformanceZip5?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    cOVID19Outlays?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    cOVID19Obligations?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    infrastructureOutlays?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    infrastructureObligations?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    defCodes?: Array<string>;
    /**
     * Sub-Awards only, returns the ID (piid/fain/uri) of the prime award.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    primeAwardID?: string | null;
    /**
     * Sub-Awards only, returns the name of the prime award's recipient.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    primeRecipientName?: string | null;
    /**
     * Sub-Awards only, return the recipient id of the prime award's recipient.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    primeAwardRecipientId?: string | null;
    /**
     * Sub-Awards only, return the award id of the prime award.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    primeAwardInternalId?: string | null;
    /**
     * Sub-Awards only, return the generated unique award id of the prime award.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    primeAwardGeneratedInternalId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    recipientDUNSNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    recipientName?: string | null;
    /**
     * A unique identifier for the recipient which includes the recipient hash and level.
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    recipientId?: string | null;
    /**
     * Assistance awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    sAINumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    startDate?: string;
    /**
     * Sub-Awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subAwardAmount?: string;
    /**
     * Sub-Awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subAwardDate?: string;
    /**
     * Sub-Awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subAwardID?: string;
    /**
     * Sub-Awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subAwardType?: string;
    /**
     * Sub-Awards only
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subAwardeeName?: string;
    /**
     * Assistance awards only
     * @type {number}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    subsidyCost?: number;
    /**
     * Returns with "Awarding Agency", is null when the agency does not have an agency profile page
     * @type {string}
     * @memberof ApiV2SearchSpendingByAwardPost200ResponseResultsInner
     */
    agencySlug?: string | null;
}

/**
 * Check if a given object implements the ApiV2SearchSpendingByAwardPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2SearchSpendingByAwardPost200ResponseResultsInner(value: object): value is ApiV2SearchSpendingByAwardPost200ResponseResultsInner {
    if (!('internalId' in value) || value['internalId'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByAwardPost200ResponseResultsInnerFromJSON(json: any): ApiV2SearchSpendingByAwardPost200ResponseResultsInner {
    return ApiV2SearchSpendingByAwardPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByAwardPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByAwardPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'internalId': json['internal_id'],
        'awardAmount': json['Award Amount'] == null ? undefined : json['Award Amount'],
        'totalOutlays': json['Total Outlays'] == null ? undefined : json['Total Outlays'],
        'awardID': json['Award ID'] == null ? undefined : json['Award ID'],
        'awardType': json['Award Type'] == null ? undefined : json['Award Type'],
        'awardingAgencyCode': json['Awarding Agency Code'] == null ? undefined : json['Awarding Agency Code'],
        'awardingAgency': json['Awarding Agency'] == null ? undefined : json['Awarding Agency'],
        'awardingAgencyId': json['awarding_agency_id'] == null ? undefined : json['awarding_agency_id'],
        'awardingSubAgencyCode': json['Awarding Sub Agency Code'] == null ? undefined : json['Awarding Sub Agency Code'],
        'awardingSubAgency': json['Awarding Sub Agency'] == null ? undefined : json['Awarding Sub Agency'],
        'baseObligationDate': json['Base Obligation Date'] == null ? undefined : json['Base Obligation Date'],
        'cFDANumber': json['CFDA Number'] == null ? undefined : json['CFDA Number'],
        'contractAwardType': json['Contract Award Type'] == null ? undefined : json['Contract Award Type'],
        'description': json['Description'] == null ? undefined : json['Description'],
        'endDate': json['End Date'] == null ? undefined : json['End Date'],
        'fundingAgencyCode': json['Funding Agency Code'] == null ? undefined : json['Funding Agency Code'],
        'fundingAgency': json['Funding Agency'] == null ? undefined : json['Funding Agency'],
        'fundingSubAgencyCode': json['Funding Sub Agency Code'] == null ? undefined : json['Funding Sub Agency Code'],
        'fundingSubAgency': json['Funding Sub Agency'] == null ? undefined : json['Funding Sub Agency'],
        'generatedInternalId': json['generated_internal_id'] == null ? undefined : json['generated_internal_id'],
        'issuedDate': json['Issued Date'] == null ? undefined : json['Issued Date'],
        'lastDateToOrder': json['Last Date to Order'] == null ? undefined : json['Last Date to Order'],
        'lastModifiedDate': json['Last Modified Date'] == null ? undefined : json['Last Modified Date'],
        'loanValue': json['Loan Value'] == null ? undefined : json['Loan Value'],
        'periodOfPerformanceCurrentEndDate': json['Period of Performance Current End Date'] == null ? undefined : json['Period of Performance Current End Date'],
        'periodOfPerformanceStartDate': json['Period of Performance Start Date'] == null ? undefined : json['Period of Performance Start Date'],
        'placeOfPerformanceCityCode': json['Place of Performance City Code'] == null ? undefined : json['Place of Performance City Code'],
        'placeOfPerformanceCountryCode': json['Place of Performance Country Code'] == null ? undefined : json['Place of Performance Country Code'],
        'placeOfPerformanceStateCode': json['Place of Performance State Code'] == null ? undefined : json['Place of Performance State Code'],
        'placeOfPerformanceZip5': json['Place of Performance Zip5'] == null ? undefined : json['Place of Performance Zip5'],
        'cOVID19Outlays': json['COVID-19 Outlays'] == null ? undefined : json['COVID-19 Outlays'],
        'cOVID19Obligations': json['COVID-19 Obligations'] == null ? undefined : json['COVID-19 Obligations'],
        'infrastructureOutlays': json['Infrastructure Outlays'] == null ? undefined : json['Infrastructure Outlays'],
        'infrastructureObligations': json['Infrastructure Obligations'] == null ? undefined : json['Infrastructure Obligations'],
        'defCodes': json['def_codes'] == null ? undefined : json['def_codes'],
        'primeAwardID': json['Prime Award ID'] == null ? undefined : json['Prime Award ID'],
        'primeRecipientName': json['Prime Recipient Name'] == null ? undefined : json['Prime Recipient Name'],
        'primeAwardRecipientId': json['prime_award_recipient_id'] == null ? undefined : json['prime_award_recipient_id'],
        'primeAwardInternalId': json['prime_award_internal_id'] == null ? undefined : json['prime_award_internal_id'],
        'primeAwardGeneratedInternalId': json['prime_award_generated_internal_id'] == null ? undefined : json['prime_award_generated_internal_id'],
        'recipientDUNSNumber': json['Recipient DUNS Number'] == null ? undefined : json['Recipient DUNS Number'],
        'recipientName': json['Recipient Name'] == null ? undefined : json['Recipient Name'],
        'recipientId': json['recipient_id'] == null ? undefined : json['recipient_id'],
        'sAINumber': json['SAI Number'] == null ? undefined : json['SAI Number'],
        'startDate': json['Start Date'] == null ? undefined : json['Start Date'],
        'subAwardAmount': json['Sub-Award Amount'] == null ? undefined : json['Sub-Award Amount'],
        'subAwardDate': json['Sub-Award Date'] == null ? undefined : json['Sub-Award Date'],
        'subAwardID': json['Sub-Award ID'] == null ? undefined : json['Sub-Award ID'],
        'subAwardType': json['Sub-Award Type'] == null ? undefined : json['Sub-Award Type'],
        'subAwardeeName': json['Sub-Awardee Name'] == null ? undefined : json['Sub-Awardee Name'],
        'subsidyCost': json['Subsidy Cost'] == null ? undefined : json['Subsidy Cost'],
        'agencySlug': json['agency_slug'] == null ? undefined : json['agency_slug'],
    };
}

export function ApiV2SearchSpendingByAwardPost200ResponseResultsInnerToJSON(json: any): ApiV2SearchSpendingByAwardPost200ResponseResultsInner {
    return ApiV2SearchSpendingByAwardPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByAwardPost200ResponseResultsInnerToJSONTyped(value?: ApiV2SearchSpendingByAwardPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'internal_id': value['internalId'],
        'Award Amount': value['awardAmount'],
        'Total Outlays': value['totalOutlays'],
        'Award ID': value['awardID'],
        'Award Type': value['awardType'],
        'Awarding Agency Code': value['awardingAgencyCode'],
        'Awarding Agency': value['awardingAgency'],
        'awarding_agency_id': value['awardingAgencyId'],
        'Awarding Sub Agency Code': value['awardingSubAgencyCode'],
        'Awarding Sub Agency': value['awardingSubAgency'],
        'Base Obligation Date': value['baseObligationDate'],
        'CFDA Number': value['cFDANumber'],
        'Contract Award Type': value['contractAwardType'],
        'Description': value['description'],
        'End Date': value['endDate'],
        'Funding Agency Code': value['fundingAgencyCode'],
        'Funding Agency': value['fundingAgency'],
        'Funding Sub Agency Code': value['fundingSubAgencyCode'],
        'Funding Sub Agency': value['fundingSubAgency'],
        'generated_internal_id': value['generatedInternalId'],
        'Issued Date': value['issuedDate'],
        'Last Date to Order': value['lastDateToOrder'],
        'Last Modified Date': value['lastModifiedDate'],
        'Loan Value': value['loanValue'],
        'Period of Performance Current End Date': value['periodOfPerformanceCurrentEndDate'],
        'Period of Performance Start Date': value['periodOfPerformanceStartDate'],
        'Place of Performance City Code': value['placeOfPerformanceCityCode'],
        'Place of Performance Country Code': value['placeOfPerformanceCountryCode'],
        'Place of Performance State Code': value['placeOfPerformanceStateCode'],
        'Place of Performance Zip5': value['placeOfPerformanceZip5'],
        'COVID-19 Outlays': value['cOVID19Outlays'],
        'COVID-19 Obligations': value['cOVID19Obligations'],
        'Infrastructure Outlays': value['infrastructureOutlays'],
        'Infrastructure Obligations': value['infrastructureObligations'],
        'def_codes': value['defCodes'],
        'Prime Award ID': value['primeAwardID'],
        'Prime Recipient Name': value['primeRecipientName'],
        'prime_award_recipient_id': value['primeAwardRecipientId'],
        'prime_award_internal_id': value['primeAwardInternalId'],
        'prime_award_generated_internal_id': value['primeAwardGeneratedInternalId'],
        'Recipient DUNS Number': value['recipientDUNSNumber'],
        'Recipient Name': value['recipientName'],
        'recipient_id': value['recipientId'],
        'SAI Number': value['sAINumber'],
        'Start Date': value['startDate'],
        'Sub-Award Amount': value['subAwardAmount'],
        'Sub-Award Date': value['subAwardDate'],
        'Sub-Award ID': value['subAwardID'],
        'Sub-Award Type': value['subAwardType'],
        'Sub-Awardee Name': value['subAwardeeName'],
        'Subsidy Cost': value['subsidyCost'],
        'agency_slug': value['agencySlug'],
    };
}

