/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2FederalAccountsPost200ResponseResultsInner } from './ApiV2FederalAccountsPost200ResponseResultsInner';
import {
    ApiV2FederalAccountsPost200ResponseResultsInnerFromJSON,
    ApiV2FederalAccountsPost200ResponseResultsInnerFromJSONTyped,
    ApiV2FederalAccountsPost200ResponseResultsInnerToJSON,
    ApiV2FederalAccountsPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2FederalAccountsPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2FederalAccountsPost200Response
 */
export interface ApiV2FederalAccountsPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    previous?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    limit: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    hasNext: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    page: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    hasPrevious: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    next: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    fy: string;
    /**
     * 
     * @type {Array<ApiV2FederalAccountsPost200ResponseResultsInner>}
     * @memberof ApiV2FederalAccountsPost200Response
     */
    results?: Array<ApiV2FederalAccountsPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2FederalAccountsPost200Response interface.
 */
export function instanceOfApiV2FederalAccountsPost200Response(value: object): value is ApiV2FederalAccountsPost200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('hasPrevious' in value) || value['hasPrevious'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('fy' in value) || value['fy'] === undefined) return false;
    return true;
}

export function ApiV2FederalAccountsPost200ResponseFromJSON(json: any): ApiV2FederalAccountsPost200Response {
    return ApiV2FederalAccountsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2FederalAccountsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalAccountsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'previous': json['previous'] == null ? undefined : json['previous'],
        'count': json['count'],
        'limit': json['limit'],
        'hasNext': json['hasNext'],
        'page': json['page'],
        'hasPrevious': json['hasPrevious'],
        'next': json['next'],
        'fy': json['fy'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ApiV2FederalAccountsPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2FederalAccountsPost200ResponseToJSON(json: any): ApiV2FederalAccountsPost200Response {
    return ApiV2FederalAccountsPost200ResponseToJSONTyped(json, false);
}

export function ApiV2FederalAccountsPost200ResponseToJSONTyped(value?: ApiV2FederalAccountsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'previous': value['previous'],
        'count': value['count'],
        'limit': value['limit'],
        'hasNext': value['hasNext'],
        'page': value['page'],
        'hasPrevious': value['hasPrevious'],
        'next': value['next'],
        'fy': value['fy'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ApiV2FederalAccountsPost200ResponseResultsInnerToJSON)),
    };
}

