/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner
 */
export interface ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner
     */
    budgetSubfunctionCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner
     */
    budgetSubfunctionTitle: string;
}

/**
 * Check if a given object implements the ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner(value: object): value is ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner {
    if (!('budgetSubfunctionCode' in value) || value['budgetSubfunctionCode'] === undefined) return false;
    if (!('budgetSubfunctionTitle' in value) || value['budgetSubfunctionTitle'] === undefined) return false;
    return true;
}

export function ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerFromJSON(json: any): ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner {
    return ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'budgetSubfunctionCode': json['budget_subfunction_code'],
        'budgetSubfunctionTitle': json['budget_subfunction_title'],
    };
}

export function ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerToJSON(json: any): ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner {
    return ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInnerToJSONTyped(value?: ApiV2BudgetFunctionsListBudgetSubfunctionsPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget_subfunction_code': value['budgetSubfunctionCode'],
        'budget_subfunction_title': value['budgetSubfunctionTitle'],
    };
}

