/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AutocompleteLocationPost200ResponseResults } from './ApiV2AutocompleteLocationPost200ResponseResults';
import {
    ApiV2AutocompleteLocationPost200ResponseResultsFromJSON,
    ApiV2AutocompleteLocationPost200ResponseResultsFromJSONTyped,
    ApiV2AutocompleteLocationPost200ResponseResultsToJSON,
    ApiV2AutocompleteLocationPost200ResponseResultsToJSONTyped,
} from './ApiV2AutocompleteLocationPost200ResponseResults';

/**
 * 
 * @export
 * @interface ApiV2AutocompleteLocationPost200Response
 */
export interface ApiV2AutocompleteLocationPost200Response {
    /**
     * 
     * @type {ApiV2AutocompleteLocationPost200ResponseResults}
     * @memberof ApiV2AutocompleteLocationPost200Response
     */
    results: ApiV2AutocompleteLocationPost200ResponseResults;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV2AutocompleteLocationPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AutocompleteLocationPost200Response interface.
 */
export function instanceOfApiV2AutocompleteLocationPost200Response(value: object): value is ApiV2AutocompleteLocationPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteLocationPost200ResponseFromJSON(json: any): ApiV2AutocompleteLocationPost200Response {
    return ApiV2AutocompleteLocationPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AutocompleteLocationPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteLocationPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ApiV2AutocompleteLocationPost200ResponseResultsFromJSON(json['results']),
        'messages': json['messages'],
    };
}

export function ApiV2AutocompleteLocationPost200ResponseToJSON(json: any): ApiV2AutocompleteLocationPost200Response {
    return ApiV2AutocompleteLocationPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AutocompleteLocationPost200ResponseToJSONTyped(value?: ApiV2AutocompleteLocationPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ApiV2AutocompleteLocationPost200ResponseResultsToJSON(value['results']),
        'messages': value['messages'],
    };
}

