/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BulkDownloadStatusPost200Response
 */
export interface ApiV2BulkDownloadStatusPost200Response {
    /**
     * Is the name of the zipfile containing CSVs that will be generated (file_name is timestamp followed by `_transactions` or `_awards`).
     * @type {string}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    fileName: string;
    /**
     * A human readable error message if the `status` is `failed`, otherwise it is `null`.
     * @type {string}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    message: string | null;
    /**
     * Is the time taken to genereate the file (if `status` is `finished` or `failed`), or time taken so far (if `running`).
     * @type {string}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    secondsElapsed: string | null;
    /**
     * A string representing the current state of the CSV generation request.
     * @type {ApiV2BulkDownloadStatusPost200ResponseStatusEnum}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    status: ApiV2BulkDownloadStatusPost200ResponseStatusEnum;
    /**
     * Is the number of columns in the CSV, or `null` if not finished.
     * @type {number}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    totalColumns: number | null;
    /**
     * Is the number of rows in the CSV, or `null` if not finished.
     * @type {number}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    totalRows: number | null;
    /**
     * Is the estimated file size of the CSV in kilobytes, or `null` if not finished.
     * @type {number}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    totalSize: number | null;
    /**
     * The URL for the file.
     * @type {string}
     * @memberof ApiV2BulkDownloadStatusPost200Response
     */
    fileUrl: string;
}


/**
 * @export
 */
export const ApiV2BulkDownloadStatusPost200ResponseStatusEnum = {
    Failed: 'failed',
    Finished: 'finished',
    Ready: 'ready',
    Running: 'running'
} as const;
export type ApiV2BulkDownloadStatusPost200ResponseStatusEnum = typeof ApiV2BulkDownloadStatusPost200ResponseStatusEnum[keyof typeof ApiV2BulkDownloadStatusPost200ResponseStatusEnum];


/**
 * Check if a given object implements the ApiV2BulkDownloadStatusPost200Response interface.
 */
export function instanceOfApiV2BulkDownloadStatusPost200Response(value: object): value is ApiV2BulkDownloadStatusPost200Response {
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('secondsElapsed' in value) || value['secondsElapsed'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalColumns' in value) || value['totalColumns'] === undefined) return false;
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    if (!('totalSize' in value) || value['totalSize'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadStatusPost200ResponseFromJSON(json: any): ApiV2BulkDownloadStatusPost200Response {
    return ApiV2BulkDownloadStatusPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadStatusPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadStatusPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['file_name'],
        'message': json['message'],
        'secondsElapsed': json['seconds_elapsed'],
        'status': json['status'],
        'totalColumns': json['total_columns'],
        'totalRows': json['total_rows'],
        'totalSize': json['total_size'],
        'fileUrl': json['file_url'],
    };
}

export function ApiV2BulkDownloadStatusPost200ResponseToJSON(json: any): ApiV2BulkDownloadStatusPost200Response {
    return ApiV2BulkDownloadStatusPost200ResponseToJSONTyped(json, false);
}

export function ApiV2BulkDownloadStatusPost200ResponseToJSONTyped(value?: ApiV2BulkDownloadStatusPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['fileName'],
        'message': value['message'],
        'seconds_elapsed': value['secondsElapsed'],
        'status': value['status'],
        'total_columns': value['totalColumns'],
        'total_rows': value['totalRows'],
        'total_size': value['totalSize'],
        'file_url': value['fileUrl'],
    };
}

