/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner
 */
export interface ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner
     */
    budgetFunctionCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner
     */
    budgetFunctionTitle: string;
}

/**
 * Check if a given object implements the ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner(value: object): value is ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner {
    if (!('budgetFunctionCode' in value) || value['budgetFunctionCode'] === undefined) return false;
    if (!('budgetFunctionTitle' in value) || value['budgetFunctionTitle'] === undefined) return false;
    return true;
}

export function ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerFromJSON(json: any): ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner {
    return ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'budgetFunctionCode': json['budget_function_code'],
        'budgetFunctionTitle': json['budget_function_title'],
    };
}

export function ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerToJSON(json: any): ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner {
    return ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInnerToJSONTyped(value?: ApiV2BudgetFunctionsListBudgetFunctionsPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'budget_function_code': value['budgetFunctionCode'],
        'budget_function_title': value['budgetFunctionTitle'],
    };
}

