/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2IdvsActivityPost200ResponsePageMetadata } from './ApiV2IdvsActivityPost200ResponsePageMetadata';
import {
    ApiV2IdvsActivityPost200ResponsePageMetadataFromJSON,
    ApiV2IdvsActivityPost200ResponsePageMetadataFromJSONTyped,
    ApiV2IdvsActivityPost200ResponsePageMetadataToJSON,
    ApiV2IdvsActivityPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2IdvsActivityPost200ResponsePageMetadata';
import type { ApiV2IdvsActivityPost200ResponseResultsInner } from './ApiV2IdvsActivityPost200ResponseResultsInner';
import {
    ApiV2IdvsActivityPost200ResponseResultsInnerFromJSON,
    ApiV2IdvsActivityPost200ResponseResultsInnerFromJSONTyped,
    ApiV2IdvsActivityPost200ResponseResultsInnerToJSON,
    ApiV2IdvsActivityPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2IdvsActivityPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2IdvsActivityPost200Response
 */
export interface ApiV2IdvsActivityPost200Response {
    /**
     * Results are sorted by obligated amount in descending order.
     * @type {Array<ApiV2IdvsActivityPost200ResponseResultsInner>}
     * @memberof ApiV2IdvsActivityPost200Response
     */
    results: Array<ApiV2IdvsActivityPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2IdvsActivityPost200ResponsePageMetadata}
     * @memberof ApiV2IdvsActivityPost200Response
     */
    pageMetadata: ApiV2IdvsActivityPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2IdvsActivityPost200Response interface.
 */
export function instanceOfApiV2IdvsActivityPost200Response(value: object): value is ApiV2IdvsActivityPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2IdvsActivityPost200ResponseFromJSON(json: any): ApiV2IdvsActivityPost200Response {
    return ApiV2IdvsActivityPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2IdvsActivityPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsActivityPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2IdvsActivityPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2IdvsActivityPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2IdvsActivityPost200ResponseToJSON(json: any): ApiV2IdvsActivityPost200Response {
    return ApiV2IdvsActivityPost200ResponseToJSONTyped(json, false);
}

export function ApiV2IdvsActivityPost200ResponseToJSONTyped(value?: ApiV2IdvsActivityPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2IdvsActivityPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2IdvsActivityPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

