/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2FederalObligationsPost200ResponsePageMetadata
 */
export interface ApiV2FederalObligationsPost200ResponsePageMetadata {
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    page: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    hasNextPage: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    hasPreviousPage: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    next: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    current: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2FederalObligationsPost200ResponsePageMetadata
     */
    previous: string | null;
}

/**
 * Check if a given object implements the ApiV2FederalObligationsPost200ResponsePageMetadata interface.
 */
export function instanceOfApiV2FederalObligationsPost200ResponsePageMetadata(value: object): value is ApiV2FederalObligationsPost200ResponsePageMetadata {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('hasNextPage' in value) || value['hasNextPage'] === undefined) return false;
    if (!('hasPreviousPage' in value) || value['hasPreviousPage'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    return true;
}

export function ApiV2FederalObligationsPost200ResponsePageMetadataFromJSON(json: any): ApiV2FederalObligationsPost200ResponsePageMetadata {
    return ApiV2FederalObligationsPost200ResponsePageMetadataFromJSONTyped(json, false);
}

export function ApiV2FederalObligationsPost200ResponsePageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalObligationsPost200ResponsePageMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'page': json['page'],
        'hasNextPage': json['has_next_page'],
        'hasPreviousPage': json['has_previous_page'],
        'next': json['next'],
        'current': json['current'],
        'previous': json['previous'],
    };
}

export function ApiV2FederalObligationsPost200ResponsePageMetadataToJSON(json: any): ApiV2FederalObligationsPost200ResponsePageMetadata {
    return ApiV2FederalObligationsPost200ResponsePageMetadataToJSONTyped(json, false);
}

export function ApiV2FederalObligationsPost200ResponsePageMetadataToJSONTyped(value?: ApiV2FederalObligationsPost200ResponsePageMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'page': value['page'],
        'has_next_page': value['hasNextPage'],
        'has_previous_page': value['hasPreviousPage'],
        'next': value['next'],
        'current': value['current'],
        'previous': value['previous'],
    };
}

