/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
 */
export interface ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner {
    /**
     * Dollar obligated or outlayed amount (depending on the `spending_type` requested)
     * @type {number}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    shapeCode: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    population: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    perCapita: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner
     */
    awardCount: number;
}

/**
 * Check if a given object implements the ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2DisasterSpendingByGeographyPost200ResponseResultsInner(value: object): value is ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('shapeCode' in value) || value['shapeCode'] === undefined) return false;
    if (!('population' in value) || value['population'] === undefined) return false;
    if (!('perCapita' in value) || value['perCapita'] === undefined) return false;
    if (!('awardCount' in value) || value['awardCount'] === undefined) return false;
    return true;
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSON(json: any): ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner {
    return ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'displayName': json['display_name'],
        'shapeCode': json['shape_code'],
        'population': json['population'],
        'perCapita': json['per_capita'],
        'awardCount': json['award_count'],
    };
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSON(json: any): ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner {
    return ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2DisasterSpendingByGeographyPost200ResponseResultsInnerToJSONTyped(value?: ApiV2DisasterSpendingByGeographyPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'display_name': value['displayName'],
        'shape_code': value['shapeCode'],
        'population': value['population'],
        'per_capita': value['perCapita'],
        'award_count': value['awardCount'],
    };
}

