/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInner } from './ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInner';
import {
    ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerFromJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerFromJSONTyped,
    ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerToJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInner';
import type { ApiV2AgencyToptierCodeDefCodePost200ResponseTotals } from './ApiV2AgencyToptierCodeDefCodePost200ResponseTotals';
import {
    ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsFromJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsFromJSONTyped,
    ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsToJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsToJSONTyped,
} from './ApiV2AgencyToptierCodeDefCodePost200ResponseTotals';
import type { ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadata } from './ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadata';
import {
    ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataFromJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataFromJSONTyped,
    ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataToJSON,
    ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2AgencyToptierCodeDefCodePost200Response
 */
export interface ApiV2AgencyToptierCodeDefCodePost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    toptierCode: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadata}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    pageMetadata: ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadata;
    /**
     * 
     * @type {ApiV2AgencyToptierCodeDefCodePost200ResponseTotals}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    totals: ApiV2AgencyToptierCodeDefCodePost200ResponseTotals;
    /**
     * 
     * @type {Array<ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInner>}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    results: Array<ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyToptierCodeDefCodePost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyToptierCodeDefCodePost200Response interface.
 */
export function instanceOfApiV2AgencyToptierCodeDefCodePost200Response(value: object): value is ApiV2AgencyToptierCodeDefCodePost200Response {
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    if (!('totals' in value) || value['totals'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyToptierCodeDefCodePost200ResponseFromJSON(json: any): ApiV2AgencyToptierCodeDefCodePost200Response {
    return ApiV2AgencyToptierCodeDefCodePost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeDefCodePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyToptierCodeDefCodePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'toptierCode': json['toptier_code'],
        'fiscalYear': json['fiscal_year'],
        'pageMetadata': ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'totals': ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsFromJSON(json['totals']),
        'results': ((json['results'] as Array<any>).map(ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'],
    };
}

export function ApiV2AgencyToptierCodeDefCodePost200ResponseToJSON(json: any): ApiV2AgencyToptierCodeDefCodePost200Response {
    return ApiV2AgencyToptierCodeDefCodePost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeDefCodePost200ResponseToJSONTyped(value?: ApiV2AgencyToptierCodeDefCodePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toptier_code': value['toptierCode'],
        'fiscal_year': value['fiscalYear'],
        'page_metadata': ApiV2AgencyToptierCodeDefCodePost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'totals': ApiV2AgencyToptierCodeDefCodePost200ResponseTotalsToJSON(value['totals']),
        'results': ((value['results'] as Array<any>).map(ApiV2AgencyToptierCodeDefCodePost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

