/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
 */
export interface ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults {
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    outlay: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    budgetAuthority: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    unobligated: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    balanceBroughtForward: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    otherBudgetaryResources: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    appropriations: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults
     */
    name: string;
}

/**
 * Check if a given object implements the ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults interface.
 */
export function instanceOfApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults(value: object): value is ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults {
    if (!('outlay' in value) || value['outlay'] === undefined) return false;
    if (!('budgetAuthority' in value) || value['budgetAuthority'] === undefined) return false;
    if (!('unobligated' in value) || value['unobligated'] === undefined) return false;
    if (!('balanceBroughtForward' in value) || value['balanceBroughtForward'] === undefined) return false;
    if (!('otherBudgetaryResources' in value) || value['otherBudgetaryResources'] === undefined) return false;
    if (!('appropriations' in value) || value['appropriations'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsFromJSON(json: any): ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults {
    return ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsFromJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults {
    if (json == null) {
        return json;
    }
    return {
        
        'outlay': json['outlay'],
        'budgetAuthority': json['budget_authority'],
        'unobligated': json['unobligated'],
        'balanceBroughtForward': json['balance_brought_forward'],
        'otherBudgetaryResources': json['other_budgetary_resources'],
        'appropriations': json['appropriations'],
        'name': json['name'],
    };
}

export function ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsToJSON(json: any): ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults {
    return ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsToJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResultsToJSONTyped(value?: ApiV2FederalAccountsFederalAccountIdFiscalYearSnapshotPost200ResponseResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outlay': value['outlay'],
        'budget_authority': value['budgetAuthority'],
        'unobligated': value['unobligated'],
        'balance_brought_forward': value['balanceBroughtForward'],
        'other_budgetary_resources': value['otherBudgetaryResources'],
        'appropriations': value['appropriations'],
        'name': value['name'],
    };
}

