/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
 */
export interface ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    abbreviation: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    activeFq: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    activeFy: string;
    /**
     * `agency_id` is the unique USAspending.gov identifier for the agency. You will need to use this ID in other endpoints when requesting detailed information about this specific agency.
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    agencyId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    agencyName: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    budgetAuthorityAmount: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    congressionalJustificationUrl: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    currentTotalBudgetAuthorityAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    obligatedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    outlayAmount: number;
    /**
     * `percentage_of_total_budget_authority` is the percentage of the agency's budget authority compared to the total government budget authority, expressed as a decimal value.
     * @type {number}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    percentageOfTotalBudgetAuthority: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    toptierCode: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner
     */
    agencySlug: string;
}

/**
 * Check if a given object implements the ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReferencesToptierAgenciesPost200ResponseResultsInner(value: object): value is ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner {
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('activeFq' in value) || value['activeFq'] === undefined) return false;
    if (!('activeFy' in value) || value['activeFy'] === undefined) return false;
    if (!('agencyId' in value) || value['agencyId'] === undefined) return false;
    if (!('agencyName' in value) || value['agencyName'] === undefined) return false;
    if (!('budgetAuthorityAmount' in value) || value['budgetAuthorityAmount'] === undefined) return false;
    if (!('congressionalJustificationUrl' in value) || value['congressionalJustificationUrl'] === undefined) return false;
    if (!('currentTotalBudgetAuthorityAmount' in value) || value['currentTotalBudgetAuthorityAmount'] === undefined) return false;
    if (!('obligatedAmount' in value) || value['obligatedAmount'] === undefined) return false;
    if (!('outlayAmount' in value) || value['outlayAmount'] === undefined) return false;
    if (!('percentageOfTotalBudgetAuthority' in value) || value['percentageOfTotalBudgetAuthority'] === undefined) return false;
    if (!('toptierCode' in value) || value['toptierCode'] === undefined) return false;
    if (!('agencySlug' in value) || value['agencySlug'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner {
    return ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'abbreviation': json['abbreviation'],
        'activeFq': json['active_fq'],
        'activeFy': json['active_fy'],
        'agencyId': json['agency_id'],
        'agencyName': json['agency_name'],
        'budgetAuthorityAmount': json['budget_authority_amount'],
        'congressionalJustificationUrl': json['congressional_justification_url'],
        'currentTotalBudgetAuthorityAmount': json['current_total_budget_authority_amount'],
        'obligatedAmount': json['obligated_amount'],
        'outlayAmount': json['outlay_amount'],
        'percentageOfTotalBudgetAuthority': json['percentage_of_total_budget_authority'],
        'toptierCode': json['toptier_code'],
        'agencySlug': json['agency_slug'],
    };
}

export function ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerToJSON(json: any): ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner {
    return ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReferencesToptierAgenciesPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReferencesToptierAgenciesPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abbreviation': value['abbreviation'],
        'active_fq': value['activeFq'],
        'active_fy': value['activeFy'],
        'agency_id': value['agencyId'],
        'agency_name': value['agencyName'],
        'budget_authority_amount': value['budgetAuthorityAmount'],
        'congressional_justification_url': value['congressionalJustificationUrl'],
        'current_total_budget_authority_amount': value['currentTotalBudgetAuthorityAmount'],
        'obligated_amount': value['obligatedAmount'],
        'outlay_amount': value['outlayAmount'],
        'percentage_of_total_budget_authority': value['percentageOfTotalBudgetAuthority'],
        'toptier_code': value['toptierCode'],
        'agency_slug': value['agencySlug'],
    };
}

