/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner
 */
export interface ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner
     */
    name: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner
     */
    amount: number | null;
}

/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner(value: object): value is ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerFromJSON(json: any): ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner {
    return ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'amount': json['amount'],
    };
}

export function ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerToJSON(json: any): ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner {
    return ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInnerToJSONTyped(value?: ApiV2AwardsAwardIdPost200ResponseExecutiveDetailsOfficersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'amount': value['amount'],
    };
}

