/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2ReferencesFilterTreePscPost200ResponseResultsInner } from './ApiV2ReferencesFilterTreePscPost200ResponseResultsInner';
import {
    ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerFromJSON,
    ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerFromJSONTyped,
    ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerToJSON,
    ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2ReferencesFilterTreePscPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2ReferencesFilterTreePscPost200Response
 */
export interface ApiV2ReferencesFilterTreePscPost200Response {
    /**
     * 
     * @type {Array<ApiV2ReferencesFilterTreePscPost200ResponseResultsInner>}
     * @memberof ApiV2ReferencesFilterTreePscPost200Response
     */
    results: Array<ApiV2ReferencesFilterTreePscPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2ReferencesFilterTreePscPost200Response interface.
 */
export function instanceOfApiV2ReferencesFilterTreePscPost200Response(value: object): value is ApiV2ReferencesFilterTreePscPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesFilterTreePscPost200ResponseFromJSON(json: any): ApiV2ReferencesFilterTreePscPost200Response {
    return ApiV2ReferencesFilterTreePscPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2ReferencesFilterTreePscPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesFilterTreePscPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2ReferencesFilterTreePscPost200ResponseToJSON(json: any): ApiV2ReferencesFilterTreePscPost200Response {
    return ApiV2ReferencesFilterTreePscPost200ResponseToJSONTyped(json, false);
}

export function ApiV2ReferencesFilterTreePscPost200ResponseToJSONTyped(value?: ApiV2ReferencesFilterTreePscPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2ReferencesFilterTreePscPost200ResponseResultsInnerToJSON)),
    };
}

