/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2SpendingPost200ResponseResultsInner } from './ApiV2SpendingPost200ResponseResultsInner';
import {
    ApiV2SpendingPost200ResponseResultsInnerFromJSON,
    ApiV2SpendingPost200ResponseResultsInnerFromJSONTyped,
    ApiV2SpendingPost200ResponseResultsInnerToJSON,
    ApiV2SpendingPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2SpendingPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2SpendingPost200Response
 */
export interface ApiV2SpendingPost200Response {
    /**
     * Total should only be null when there are no results.
     * @type {number}
     * @memberof ApiV2SpendingPost200Response
     */
    total: number | null;
    /**
     * This is the "as-of" date for the data being returned.
     * @type {string}
     * @memberof ApiV2SpendingPost200Response
     */
    endDate: string;
    /**
     * 
     * @type {Array<ApiV2SpendingPost200ResponseResultsInner>}
     * @memberof ApiV2SpendingPost200Response
     */
    results: Array<ApiV2SpendingPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2SpendingPost200Response interface.
 */
export function instanceOfApiV2SpendingPost200Response(value: object): value is ApiV2SpendingPost200Response {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2SpendingPost200ResponseFromJSON(json: any): ApiV2SpendingPost200Response {
    return ApiV2SpendingPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2SpendingPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SpendingPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'endDate': json['end_date'],
        'results': ((json['results'] as Array<any>).map(ApiV2SpendingPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2SpendingPost200ResponseToJSON(json: any): ApiV2SpendingPost200Response {
    return ApiV2SpendingPost200ResponseToJSONTyped(json, false);
}

export function ApiV2SpendingPost200ResponseToJSONTyped(value?: ApiV2SpendingPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'end_date': value['endDate'],
        'results': ((value['results'] as Array<any>).map(ApiV2SpendingPost200ResponseResultsInnerToJSON)),
    };
}

