/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReferencesNaicsCodePost200ResponseResultsInner
 */
export interface ApiV2ReferencesNaicsCodePost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesNaicsCodePost200ResponseResultsInner
     */
    naics: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReferencesNaicsCodePost200ResponseResultsInner
     */
    naicsDescription: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReferencesNaicsCodePost200ResponseResultsInner
     */
    count: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2ReferencesNaicsCodePost200ResponseResultsInner
     */
    children?: Array<object>;
}

/**
 * Check if a given object implements the ApiV2ReferencesNaicsCodePost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReferencesNaicsCodePost200ResponseResultsInner(value: object): value is ApiV2ReferencesNaicsCodePost200ResponseResultsInner {
    if (!('naics' in value) || value['naics'] === undefined) return false;
    if (!('naicsDescription' in value) || value['naicsDescription'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ApiV2ReferencesNaicsCodePost200ResponseResultsInnerFromJSON(json: any): ApiV2ReferencesNaicsCodePost200ResponseResultsInner {
    return ApiV2ReferencesNaicsCodePost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReferencesNaicsCodePost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReferencesNaicsCodePost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'naics': json['naics'],
        'naicsDescription': json['naics_description'],
        'count': json['count'],
        'children': json['children'] == null ? undefined : json['children'],
    };
}

export function ApiV2ReferencesNaicsCodePost200ResponseResultsInnerToJSON(json: any): ApiV2ReferencesNaicsCodePost200ResponseResultsInner {
    return ApiV2ReferencesNaicsCodePost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReferencesNaicsCodePost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReferencesNaicsCodePost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'naics': value['naics'],
        'naics_description': value['naicsDescription'],
        'count': value['count'],
        'children': value['children'],
    };
}

