/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner
 */
export interface ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner
     */
    publicationDate: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner
     */
    certificationDate: string | null;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner(value: object): value is ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner {
    if (!('publicationDate' in value) || value['publicationDate'] === undefined) return false;
    if (!('certificationDate' in value) || value['certificationDate'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'publicationDate': json['publication_date'],
        'certificationDate': json['certification_date'],
    };
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerToJSON(json: any): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodSubmissionHistoryPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publication_date': value['publicationDate'],
        'certification_date': value['certificationDate'],
    };
}

