/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DisasterRecipientLoansPost200ResponseResultsInner
 */
export interface ApiV2DisasterRecipientLoansPost200ResponseResultsInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    id: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    description: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    children?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    awardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    faceValueOfLoan: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    obligation: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterRecipientLoansPost200ResponseResultsInner
     */
    outlay: number | null;
}

/**
 * Check if a given object implements the ApiV2DisasterRecipientLoansPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2DisasterRecipientLoansPost200ResponseResultsInner(value: object): value is ApiV2DisasterRecipientLoansPost200ResponseResultsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('awardCount' in value) || value['awardCount'] === undefined) return false;
    if (!('faceValueOfLoan' in value) || value['faceValueOfLoan'] === undefined) return false;
    if (!('obligation' in value) || value['obligation'] === undefined) return false;
    if (!('outlay' in value) || value['outlay'] === undefined) return false;
    return true;
}

export function ApiV2DisasterRecipientLoansPost200ResponseResultsInnerFromJSON(json: any): ApiV2DisasterRecipientLoansPost200ResponseResultsInner {
    return ApiV2DisasterRecipientLoansPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2DisasterRecipientLoansPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterRecipientLoansPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'description': json['description'],
        'children': json['children'] == null ? undefined : json['children'],
        'awardCount': json['award_count'],
        'faceValueOfLoan': json['face_value_of_loan'],
        'obligation': json['obligation'],
        'outlay': json['outlay'],
    };
}

export function ApiV2DisasterRecipientLoansPost200ResponseResultsInnerToJSON(json: any): ApiV2DisasterRecipientLoansPost200ResponseResultsInner {
    return ApiV2DisasterRecipientLoansPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2DisasterRecipientLoansPost200ResponseResultsInnerToJSONTyped(value?: ApiV2DisasterRecipientLoansPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'description': value['description'],
        'children': value['children'],
        'award_count': value['awardCount'],
        'face_value_of_loan': value['faceValueOfLoan'],
        'obligation': value['obligation'],
        'outlay': value['outlay'],
    };
}

