/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
 */
export interface ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
     */
    totalBudgetaryResources: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
     */
    obligatedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner
     */
    grossOutlayAmount: number;
}

/**
 * Check if a given object implements the ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner interface.
 */
export function instanceOfApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner(value: object): value is ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('totalBudgetaryResources' in value) || value['totalBudgetaryResources'] === undefined) return false;
    if (!('obligatedAmount' in value) || value['obligatedAmount'] === undefined) return false;
    if (!('grossOutlayAmount' in value) || value['grossOutlayAmount'] === undefined) return false;
    return true;
}

export function ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerFromJSON(json: any): ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner {
    return ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerFromJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'code': json['code'],
        'totalBudgetaryResources': json['total_budgetary_resources'],
        'obligatedAmount': json['obligated_amount'],
        'grossOutlayAmount': json['gross_outlay_amount'],
    };
}

export function ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerToJSON(json: any): ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner {
    return ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerToJSONTyped(json, false);
}

export function ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInnerToJSONTyped(value?: ApiV2AgencyToptierCodeFederalAccountPost200ResponseResultsInnerChildrenInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'total_budgetary_resources': value['totalBudgetaryResources'],
        'obligated_amount': value['obligatedAmount'],
        'gross_outlay_amount': value['grossOutlayAmount'],
    };
}

