/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2IdvsAmountsAwardIdPost200Response
 */
export interface ApiV2IdvsAmountsAwardIdPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    awardId: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    generatedUniqueAwardId: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childIdvCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAwardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAwardTotalObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAwardBaseAndAllOptionsValue: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAwardBaseExercisedOptionsVal: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childTotalAccountOutlay: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childTotalAccountObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAwardTotalOutlay: number | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAccountOutlaysByDefc: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    childAccountObligationsByDefc: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAwardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAwardTotalObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAwardBaseAndAllOptionsValue: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAwardBaseExercisedOptionsVal: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildTotalAccountOutlay: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildTotalAccountObligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAwardTotalOutlay: number | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAccountOutlaysByDefc: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof ApiV2IdvsAmountsAwardIdPost200Response
     */
    grandchildAccountObligationsByDefc: Array<object>;
}

/**
 * Check if a given object implements the ApiV2IdvsAmountsAwardIdPost200Response interface.
 */
export function instanceOfApiV2IdvsAmountsAwardIdPost200Response(value: object): value is ApiV2IdvsAmountsAwardIdPost200Response {
    if (!('awardId' in value) || value['awardId'] === undefined) return false;
    if (!('generatedUniqueAwardId' in value) || value['generatedUniqueAwardId'] === undefined) return false;
    if (!('childIdvCount' in value) || value['childIdvCount'] === undefined) return false;
    if (!('childAwardCount' in value) || value['childAwardCount'] === undefined) return false;
    if (!('childAwardTotalObligation' in value) || value['childAwardTotalObligation'] === undefined) return false;
    if (!('childAwardBaseAndAllOptionsValue' in value) || value['childAwardBaseAndAllOptionsValue'] === undefined) return false;
    if (!('childAwardBaseExercisedOptionsVal' in value) || value['childAwardBaseExercisedOptionsVal'] === undefined) return false;
    if (!('childTotalAccountOutlay' in value) || value['childTotalAccountOutlay'] === undefined) return false;
    if (!('childTotalAccountObligation' in value) || value['childTotalAccountObligation'] === undefined) return false;
    if (!('childAwardTotalOutlay' in value) || value['childAwardTotalOutlay'] === undefined) return false;
    if (!('childAccountOutlaysByDefc' in value) || value['childAccountOutlaysByDefc'] === undefined) return false;
    if (!('childAccountObligationsByDefc' in value) || value['childAccountObligationsByDefc'] === undefined) return false;
    if (!('grandchildAwardCount' in value) || value['grandchildAwardCount'] === undefined) return false;
    if (!('grandchildAwardTotalObligation' in value) || value['grandchildAwardTotalObligation'] === undefined) return false;
    if (!('grandchildAwardBaseAndAllOptionsValue' in value) || value['grandchildAwardBaseAndAllOptionsValue'] === undefined) return false;
    if (!('grandchildAwardBaseExercisedOptionsVal' in value) || value['grandchildAwardBaseExercisedOptionsVal'] === undefined) return false;
    if (!('grandchildTotalAccountOutlay' in value) || value['grandchildTotalAccountOutlay'] === undefined) return false;
    if (!('grandchildTotalAccountObligation' in value) || value['grandchildTotalAccountObligation'] === undefined) return false;
    if (!('grandchildAwardTotalOutlay' in value) || value['grandchildAwardTotalOutlay'] === undefined) return false;
    if (!('grandchildAccountOutlaysByDefc' in value) || value['grandchildAccountOutlaysByDefc'] === undefined) return false;
    if (!('grandchildAccountObligationsByDefc' in value) || value['grandchildAccountObligationsByDefc'] === undefined) return false;
    return true;
}

export function ApiV2IdvsAmountsAwardIdPost200ResponseFromJSON(json: any): ApiV2IdvsAmountsAwardIdPost200Response {
    return ApiV2IdvsAmountsAwardIdPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2IdvsAmountsAwardIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsAmountsAwardIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'awardId': json['award_id'],
        'generatedUniqueAwardId': json['generated_unique_award_id'],
        'childIdvCount': json['child_idv_count'],
        'childAwardCount': json['child_award_count'],
        'childAwardTotalObligation': json['child_award_total_obligation'],
        'childAwardBaseAndAllOptionsValue': json['child_award_base_and_all_options_value'],
        'childAwardBaseExercisedOptionsVal': json['child_award_base_exercised_options_val'],
        'childTotalAccountOutlay': json['child_total_account_outlay'],
        'childTotalAccountObligation': json['child_total_account_obligation'],
        'childAwardTotalOutlay': json['child_award_total_outlay'],
        'childAccountOutlaysByDefc': json['child_account_outlays_by_defc'],
        'childAccountObligationsByDefc': json['child_account_obligations_by_defc'],
        'grandchildAwardCount': json['grandchild_award_count'],
        'grandchildAwardTotalObligation': json['grandchild_award_total_obligation'],
        'grandchildAwardBaseAndAllOptionsValue': json['grandchild_award_base_and_all_options_value'],
        'grandchildAwardBaseExercisedOptionsVal': json['grandchild_award_base_exercised_options_val'],
        'grandchildTotalAccountOutlay': json['grandchild_total_account_outlay'],
        'grandchildTotalAccountObligation': json['grandchild_total_account_obligation'],
        'grandchildAwardTotalOutlay': json['grandchild_award_total_outlay'],
        'grandchildAccountOutlaysByDefc': json['grandchild_account_outlays_by_defc'],
        'grandchildAccountObligationsByDefc': json['grandchild_account_obligations_by_defc'],
    };
}

export function ApiV2IdvsAmountsAwardIdPost200ResponseToJSON(json: any): ApiV2IdvsAmountsAwardIdPost200Response {
    return ApiV2IdvsAmountsAwardIdPost200ResponseToJSONTyped(json, false);
}

export function ApiV2IdvsAmountsAwardIdPost200ResponseToJSONTyped(value?: ApiV2IdvsAmountsAwardIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'award_id': value['awardId'],
        'generated_unique_award_id': value['generatedUniqueAwardId'],
        'child_idv_count': value['childIdvCount'],
        'child_award_count': value['childAwardCount'],
        'child_award_total_obligation': value['childAwardTotalObligation'],
        'child_award_base_and_all_options_value': value['childAwardBaseAndAllOptionsValue'],
        'child_award_base_exercised_options_val': value['childAwardBaseExercisedOptionsVal'],
        'child_total_account_outlay': value['childTotalAccountOutlay'],
        'child_total_account_obligation': value['childTotalAccountObligation'],
        'child_award_total_outlay': value['childAwardTotalOutlay'],
        'child_account_outlays_by_defc': value['childAccountOutlaysByDefc'],
        'child_account_obligations_by_defc': value['childAccountObligationsByDefc'],
        'grandchild_award_count': value['grandchildAwardCount'],
        'grandchild_award_total_obligation': value['grandchildAwardTotalObligation'],
        'grandchild_award_base_and_all_options_value': value['grandchildAwardBaseAndAllOptionsValue'],
        'grandchild_award_base_exercised_options_val': value['grandchildAwardBaseExercisedOptionsVal'],
        'grandchild_total_account_outlay': value['grandchildTotalAccountOutlay'],
        'grandchild_total_account_obligation': value['grandchildTotalAccountObligation'],
        'grandchild_award_total_outlay': value['grandchildAwardTotalOutlay'],
        'grandchild_account_outlays_by_defc': value['grandchildAccountOutlaysByDefc'],
        'grandchild_account_obligations_by_defc': value['grandchildAccountObligationsByDefc'],
    };
}

