/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency
 */
export interface ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency
     */
    abbreviation: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency
     */
    slug: string | null;
}

/**
 * Check if a given object implements the ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency interface.
 */
export function instanceOfApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency(value: object): value is ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSON(json: any): ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency {
    return ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'code': json['code'],
        'abbreviation': json['abbreviation'],
        'slug': json['slug'],
    };
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSON(json: any): ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency {
    return ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSONTyped(json, false);
}

export function ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgencyToJSONTyped(value?: ApiV2AwardsAwardIdPost200ResponseAwardingAgencyToptierAgency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'code': value['code'],
        'abbreviation': value['abbreviation'],
        'slug': value['slug'],
    };
}

