/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency
 */
export interface ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency
     */
    abbreviation: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency
     */
    code: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency
     */
    name: string;
}

/**
 * Check if a given object implements the ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency interface.
 */
export function instanceOfApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency(value: object): value is ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency {
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyFromJSON(json: any): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency {
    return ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyFromJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency {
    if (json == null) {
        return json;
    }
    return {
        
        'abbreviation': json['abbreviation'],
        'code': json['code'],
        'name': json['name'],
    };
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyToJSON(json: any): ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency {
    return ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyToJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgencyToJSONTyped(value?: ApiV2AutocompleteAwardingAgencyOfficePost200ResponseResultsInnerOfficeSubtierAgency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abbreviation': value['abbreviation'],
        'code': value['code'],
        'name': value['name'],
    };
}

