/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2BulkDownloadListAgenciesPost200ResponseAgencies } from './ApiV2BulkDownloadListAgenciesPost200ResponseAgencies';
import {
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSONTyped,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSONTyped,
} from './ApiV2BulkDownloadListAgenciesPost200ResponseAgencies';
import type { ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner } from './ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner';
import {
    ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSONTyped,
    ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSON,
    ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSONTyped,
} from './ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner';

/**
 * 
 * @export
 * @interface ApiV2BulkDownloadListAgenciesPost200Response
 */
export interface ApiV2BulkDownloadListAgenciesPost200Response {
    /**
     * 
     * @type {ApiV2BulkDownloadListAgenciesPost200ResponseAgencies}
     * @memberof ApiV2BulkDownloadListAgenciesPost200Response
     */
    agencies: ApiV2BulkDownloadListAgenciesPost200ResponseAgencies;
    /**
     * 
     * @type {Array<ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner>}
     * @memberof ApiV2BulkDownloadListAgenciesPost200Response
     */
    subAgencies: Array<ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInner>;
}

/**
 * Check if a given object implements the ApiV2BulkDownloadListAgenciesPost200Response interface.
 */
export function instanceOfApiV2BulkDownloadListAgenciesPost200Response(value: object): value is ApiV2BulkDownloadListAgenciesPost200Response {
    if (!('agencies' in value) || value['agencies'] === undefined) return false;
    if (!('subAgencies' in value) || value['subAgencies'] === undefined) return false;
    return true;
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseFromJSON(json: any): ApiV2BulkDownloadListAgenciesPost200Response {
    return ApiV2BulkDownloadListAgenciesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2BulkDownloadListAgenciesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'agencies': ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesFromJSON(json['agencies']),
        'subAgencies': ((json['sub_agencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerFromJSON)),
    };
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseToJSON(json: any): ApiV2BulkDownloadListAgenciesPost200Response {
    return ApiV2BulkDownloadListAgenciesPost200ResponseToJSONTyped(json, false);
}

export function ApiV2BulkDownloadListAgenciesPost200ResponseToJSONTyped(value?: ApiV2BulkDownloadListAgenciesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agencies': ApiV2BulkDownloadListAgenciesPost200ResponseAgenciesToJSON(value['agencies']),
        'sub_agencies': ((value['subAgencies'] as Array<any>).map(ApiV2BulkDownloadListAgenciesPost200ResponseSubAgenciesInnerToJSON)),
    };
}

