/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2DisasterAgencyLoansPost200ResponsePageMetadata } from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import {
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSONTyped,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON,
    ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2DisasterAgencyLoansPost200ResponsePageMetadata';
import type { ApiV2DisasterCfdaSpendingPost200ResponseTotals } from './ApiV2DisasterCfdaSpendingPost200ResponseTotals';
import {
    ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSON,
    ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSONTyped,
    ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSON,
    ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSONTyped,
} from './ApiV2DisasterCfdaSpendingPost200ResponseTotals';
import type { ApiV2DisasterCfdaSpendingPost200ResponseResultsInner } from './ApiV2DisasterCfdaSpendingPost200ResponseResultsInner';
import {
    ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerFromJSON,
    ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerFromJSONTyped,
    ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerToJSON,
    ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2DisasterCfdaSpendingPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2DisasterCfdaSpendingPost200Response
 */
export interface ApiV2DisasterCfdaSpendingPost200Response {
    /**
     * 
     * @type {ApiV2DisasterCfdaSpendingPost200ResponseTotals}
     * @memberof ApiV2DisasterCfdaSpendingPost200Response
     */
    totals: ApiV2DisasterCfdaSpendingPost200ResponseTotals;
    /**
     * 
     * @type {Array<ApiV2DisasterCfdaSpendingPost200ResponseResultsInner>}
     * @memberof ApiV2DisasterCfdaSpendingPost200Response
     */
    results: Array<ApiV2DisasterCfdaSpendingPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2DisasterAgencyLoansPost200ResponsePageMetadata}
     * @memberof ApiV2DisasterCfdaSpendingPost200Response
     */
    pageMetadata: ApiV2DisasterAgencyLoansPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2DisasterCfdaSpendingPost200Response interface.
 */
export function instanceOfApiV2DisasterCfdaSpendingPost200Response(value: object): value is ApiV2DisasterCfdaSpendingPost200Response {
    if (!('totals' in value) || value['totals'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2DisasterCfdaSpendingPost200ResponseFromJSON(json: any): ApiV2DisasterCfdaSpendingPost200Response {
    return ApiV2DisasterCfdaSpendingPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2DisasterCfdaSpendingPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterCfdaSpendingPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totals': ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSON(json['totals']),
        'results': ((json['results'] as Array<any>).map(ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2DisasterCfdaSpendingPost200ResponseToJSON(json: any): ApiV2DisasterCfdaSpendingPost200Response {
    return ApiV2DisasterCfdaSpendingPost200ResponseToJSONTyped(json, false);
}

export function ApiV2DisasterCfdaSpendingPost200ResponseToJSONTyped(value?: ApiV2DisasterCfdaSpendingPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totals': ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSON(value['totals']),
        'results': ((value['results'] as Array<any>).map(ApiV2DisasterCfdaSpendingPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2DisasterAgencyLoansPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

