/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardsFundingPost200ResponsePageMetadata
 */
export interface ApiV2AwardsFundingPost200ResponsePageMetadata {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingPost200ResponsePageMetadata
     */
    page: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2AwardsFundingPost200ResponsePageMetadata
     */
    hasNext: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2AwardsFundingPost200ResponsePageMetadata
     */
    hasPrevious: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingPost200ResponsePageMetadata
     */
    next: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AwardsFundingPost200ResponsePageMetadata
     */
    previous: number | null;
}

/**
 * Check if a given object implements the ApiV2AwardsFundingPost200ResponsePageMetadata interface.
 */
export function instanceOfApiV2AwardsFundingPost200ResponsePageMetadata(value: object): value is ApiV2AwardsFundingPost200ResponsePageMetadata {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('hasPrevious' in value) || value['hasPrevious'] === undefined) return false;
    if (!('next' in value) || value['next'] === undefined) return false;
    if (!('previous' in value) || value['previous'] === undefined) return false;
    return true;
}

export function ApiV2AwardsFundingPost200ResponsePageMetadataFromJSON(json: any): ApiV2AwardsFundingPost200ResponsePageMetadata {
    return ApiV2AwardsFundingPost200ResponsePageMetadataFromJSONTyped(json, false);
}

export function ApiV2AwardsFundingPost200ResponsePageMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardsFundingPost200ResponsePageMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'hasNext': json['hasNext'],
        'hasPrevious': json['hasPrevious'],
        'next': json['next'],
        'previous': json['previous'],
    };
}

export function ApiV2AwardsFundingPost200ResponsePageMetadataToJSON(json: any): ApiV2AwardsFundingPost200ResponsePageMetadata {
    return ApiV2AwardsFundingPost200ResponsePageMetadataToJSONTyped(json, false);
}

export function ApiV2AwardsFundingPost200ResponsePageMetadataToJSONTyped(value?: ApiV2AwardsFundingPost200ResponsePageMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'hasNext': value['hasNext'],
        'hasPrevious': value['hasPrevious'],
        'next': value['next'],
        'previous': value['previous'],
    };
}

