/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DisasterCfdaSpendingPost200ResponseTotals
 */
export interface ApiV2DisasterCfdaSpendingPost200ResponseTotals {
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterCfdaSpendingPost200ResponseTotals
     */
    awardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterCfdaSpendingPost200ResponseTotals
     */
    obligation: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2DisasterCfdaSpendingPost200ResponseTotals
     */
    outlay: number;
}

/**
 * Check if a given object implements the ApiV2DisasterCfdaSpendingPost200ResponseTotals interface.
 */
export function instanceOfApiV2DisasterCfdaSpendingPost200ResponseTotals(value: object): value is ApiV2DisasterCfdaSpendingPost200ResponseTotals {
    if (!('awardCount' in value) || value['awardCount'] === undefined) return false;
    if (!('obligation' in value) || value['obligation'] === undefined) return false;
    if (!('outlay' in value) || value['outlay'] === undefined) return false;
    return true;
}

export function ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSON(json: any): ApiV2DisasterCfdaSpendingPost200ResponseTotals {
    return ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSONTyped(json, false);
}

export function ApiV2DisasterCfdaSpendingPost200ResponseTotalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DisasterCfdaSpendingPost200ResponseTotals {
    if (json == null) {
        return json;
    }
    return {
        
        'awardCount': json['award_count'],
        'obligation': json['obligation'],
        'outlay': json['outlay'],
    };
}

export function ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSON(json: any): ApiV2DisasterCfdaSpendingPost200ResponseTotals {
    return ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSONTyped(json, false);
}

export function ApiV2DisasterCfdaSpendingPost200ResponseTotalsToJSONTyped(value?: ApiV2DisasterCfdaSpendingPost200ResponseTotals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'award_count': value['awardCount'],
        'obligation': value['obligation'],
        'outlay': value['outlay'],
    };
}

