/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2IdvsCountFederalAccountAwardIdPost200Response
 */
export interface ApiV2IdvsCountFederalAccountAwardIdPost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2IdvsCountFederalAccountAwardIdPost200Response
     */
    count: number;
    /**
     * {
     *     "count": 2
     * }
     * @type {string}
     * @memberof ApiV2IdvsCountFederalAccountAwardIdPost200Response
     */
    body?: string;
}

/**
 * Check if a given object implements the ApiV2IdvsCountFederalAccountAwardIdPost200Response interface.
 */
export function instanceOfApiV2IdvsCountFederalAccountAwardIdPost200Response(value: object): value is ApiV2IdvsCountFederalAccountAwardIdPost200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ApiV2IdvsCountFederalAccountAwardIdPost200ResponseFromJSON(json: any): ApiV2IdvsCountFederalAccountAwardIdPost200Response {
    return ApiV2IdvsCountFederalAccountAwardIdPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2IdvsCountFederalAccountAwardIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsCountFederalAccountAwardIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'body': json['Body'] == null ? undefined : json['Body'],
    };
}

export function ApiV2IdvsCountFederalAccountAwardIdPost200ResponseToJSON(json: any): ApiV2IdvsCountFederalAccountAwardIdPost200Response {
    return ApiV2IdvsCountFederalAccountAwardIdPost200ResponseToJSONTyped(json, false);
}

export function ApiV2IdvsCountFederalAccountAwardIdPost200ResponseToJSONTyped(value?: ApiV2IdvsCountFederalAccountAwardIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'Body': value['body'],
    };
}

