/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInner } from './ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInner';
import {
    ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerFromJSON,
    ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerFromJSONTyped,
    ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerToJSON,
    ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response
 */
export interface ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response {
    /**
     * 
     * @type {Array<ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInner>}
     * @memberof ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response
     */
    results: Array<ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response interface.
 */
export function instanceOfApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response(value: object): value is ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseFromJSON(json: any): ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response {
    return ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseToJSON(json: any): ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response {
    return ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseToJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseToJSONTyped(value?: ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountIdAvailableObjectClassesPost200ResponseResultsInnerToJSON)),
    };
}

