/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInner } from './ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInner';
import {
    ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerFromJSON,
    ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerFromJSONTyped,
    ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerToJSON,
    ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerToJSONTyped,
} from './ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInner';

/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
 */
export interface ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    fiscalYear: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    fiscalPeriod: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    currentTotalBudgetAuthorityAmount: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    totalBudgetaryResources: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    percentOfTotalBudgetaryResources: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    recentPublicationDate: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    recentPublicationDateCertified: boolean;
    /**
     * 
     * @type {Array<ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInner>}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    tasAccountDiscrepanciesTotals: Array<ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInner>;
    /**
     * The difference in file A and file B obligations.
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    obligationDifference: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    unlinkedContractAwardCount: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    unlinkedAssistanceAwardCount: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner
     */
    assuranceStatementUrl: string | null;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner(value: object): value is ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner {
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('fiscalPeriod' in value) || value['fiscalPeriod'] === undefined) return false;
    if (!('currentTotalBudgetAuthorityAmount' in value) || value['currentTotalBudgetAuthorityAmount'] === undefined) return false;
    if (!('totalBudgetaryResources' in value) || value['totalBudgetaryResources'] === undefined) return false;
    if (!('percentOfTotalBudgetaryResources' in value) || value['percentOfTotalBudgetaryResources'] === undefined) return false;
    if (!('recentPublicationDate' in value) || value['recentPublicationDate'] === undefined) return false;
    if (!('recentPublicationDateCertified' in value) || value['recentPublicationDateCertified'] === undefined) return false;
    if (!('tasAccountDiscrepanciesTotals' in value) || value['tasAccountDiscrepanciesTotals'] === undefined) return false;
    if (!('obligationDifference' in value) || value['obligationDifference'] === undefined) return false;
    if (!('unlinkedContractAwardCount' in value) || value['unlinkedContractAwardCount'] === undefined) return false;
    if (!('unlinkedAssistanceAwardCount' in value) || value['unlinkedAssistanceAwardCount'] === undefined) return false;
    if (!('assuranceStatementUrl' in value) || value['assuranceStatementUrl'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'fiscalYear': json['fiscal_year'],
        'fiscalPeriod': json['fiscal_period'],
        'currentTotalBudgetAuthorityAmount': json['current_total_budget_authority_amount'],
        'totalBudgetaryResources': json['total_budgetary_resources'],
        'percentOfTotalBudgetaryResources': json['percent_of_total_budgetary_resources'],
        'recentPublicationDate': json['recent_publication_date'],
        'recentPublicationDateCertified': json['recent_publication_date_certified'],
        'tasAccountDiscrepanciesTotals': ((json['tas_account_discrepancies_totals'] as Array<any>).map(ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerFromJSON)),
        'obligationDifference': json['obligation_difference'],
        'unlinkedContractAwardCount': json['unlinked_contract_award_count'],
        'unlinkedAssistanceAwardCount': json['unlinked_assistance_award_count'],
        'assuranceStatementUrl': json['assurance_statement_url'],
    };
}

export function ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerToJSON(json: any): ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner {
    return ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInnerToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeOverviewPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fiscal_year': value['fiscalYear'],
        'fiscal_period': value['fiscalPeriod'],
        'current_total_budget_authority_amount': value['currentTotalBudgetAuthorityAmount'],
        'total_budgetary_resources': value['totalBudgetaryResources'],
        'percent_of_total_budgetary_resources': value['percentOfTotalBudgetaryResources'],
        'recent_publication_date': value['recentPublicationDate'],
        'recent_publication_date_certified': value['recentPublicationDateCertified'],
        'tas_account_discrepancies_totals': ((value['tasAccountDiscrepanciesTotals'] as Array<any>).map(ApiV2ReportingAgenciesOverviewPost200ResponseResultsInnerTasAccountDiscrepanciesTotalsInnerToJSON)),
        'obligation_difference': value['obligationDifference'],
        'unlinked_contract_award_count': value['unlinkedContractAwardCount'],
        'unlinked_assistance_award_count': value['unlinkedAssistanceAwardCount'],
        'assurance_statement_url': value['assuranceStatementUrl'],
    };
}

