/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
 */
export interface ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes {
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    grants: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    loans: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    contracts: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    directPayments: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    other: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes
     */
    idvs: number;
}

/**
 * Check if a given object implements the ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes interface.
 */
export function instanceOfApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes(value: object): value is ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes {
    if (!('grants' in value) || value['grants'] === undefined) return false;
    if (!('loans' in value) || value['loans'] === undefined) return false;
    if (!('contracts' in value) || value['contracts'] === undefined) return false;
    if (!('directPayments' in value) || value['directPayments'] === undefined) return false;
    if (!('other' in value) || value['other'] === undefined) return false;
    if (!('idvs' in value) || value['idvs'] === undefined) return false;
    return true;
}

export function ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesFromJSON(json: any): ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes {
    return ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesFromJSONTyped(json, false);
}

export function ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes {
    if (json == null) {
        return json;
    }
    return {
        
        'grants': json['grants'],
        'loans': json['loans'],
        'contracts': json['contracts'],
        'directPayments': json['direct_payments'],
        'other': json['other'],
        'idvs': json['idvs'],
    };
}

export function ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesToJSON(json: any): ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes {
    return ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesToJSONTyped(json, false);
}

export function ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypesToJSONTyped(value?: ApiV2AgencyAwardsCountPost200ResponseResultsInnerAwardTypes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grants': value['grants'],
        'loans': value['loans'],
        'contracts': value['contracts'],
        'direct_payments': value['directPayments'],
        'other': value['other'],
        'idvs': value['idvs'],
    };
}

