/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
 */
export interface ApiV2SearchSpendingByGeographyPost200ResponseResultsInner {
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    aggregatedAmount: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    shapeCode: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    population: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    perCapita: number | null;
    /**
     * 
     * @type {number}
     * @memberof ApiV2SearchSpendingByGeographyPost200ResponseResultsInner
     */
    totalOutlays?: number;
}

/**
 * Check if a given object implements the ApiV2SearchSpendingByGeographyPost200ResponseResultsInner interface.
 */
export function instanceOfApiV2SearchSpendingByGeographyPost200ResponseResultsInner(value: object): value is ApiV2SearchSpendingByGeographyPost200ResponseResultsInner {
    if (!('aggregatedAmount' in value) || value['aggregatedAmount'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('shapeCode' in value) || value['shapeCode'] === undefined) return false;
    if (!('population' in value) || value['population'] === undefined) return false;
    if (!('perCapita' in value) || value['perCapita'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSON(json: any): ApiV2SearchSpendingByGeographyPost200ResponseResultsInner {
    return ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByGeographyPost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'aggregatedAmount': json['aggregated_amount'],
        'displayName': json['display_name'],
        'shapeCode': json['shape_code'],
        'population': json['population'],
        'perCapita': json['per_capita'],
        'totalOutlays': json['total_outlays'] == null ? undefined : json['total_outlays'],
    };
}

export function ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSON(json: any): ApiV2SearchSpendingByGeographyPost200ResponseResultsInner {
    return ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSONTyped(value?: ApiV2SearchSpendingByGeographyPost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aggregated_amount': value['aggregatedAmount'],
        'display_name': value['displayName'],
        'shape_code': value['shapeCode'],
        'population': value['population'],
        'per_capita': value['perCapita'],
        'total_outlays': value['totalOutlays'],
    };
}

