/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2SearchSpendingByGeographyPost200ResponseResultsInner } from './ApiV2SearchSpendingByGeographyPost200ResponseResultsInner';
import {
    ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSON,
    ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSONTyped,
    ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSON,
    ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2SearchSpendingByGeographyPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2SearchSpendingByGeographyPost200Response
 */
export interface ApiV2SearchSpendingByGeographyPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByGeographyPost200Response
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV2SearchSpendingByGeographyPost200Response
     */
    geoLayer?: string;
    /**
     * Spending level value that was provided in the request.
     * @type {ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum}
     * @memberof ApiV2SearchSpendingByGeographyPost200Response
     */
    spendingLevel: ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum;
    /**
     * 
     * @type {Array<ApiV2SearchSpendingByGeographyPost200ResponseResultsInner>}
     * @memberof ApiV2SearchSpendingByGeographyPost200Response
     */
    results?: Array<ApiV2SearchSpendingByGeographyPost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string | null>}
     * @memberof ApiV2SearchSpendingByGeographyPost200Response
     */
    messages?: Array<string | null>;
}


/**
 * @export
 */
export const ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum = {
    Transactions: 'transactions',
    Awards: 'awards',
    Subawards: 'subawards'
} as const;
export type ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum = typeof ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum[keyof typeof ApiV2SearchSpendingByGeographyPost200ResponseSpendingLevelEnum];


/**
 * Check if a given object implements the ApiV2SearchSpendingByGeographyPost200Response interface.
 */
export function instanceOfApiV2SearchSpendingByGeographyPost200Response(value: object): value is ApiV2SearchSpendingByGeographyPost200Response {
    if (!('spendingLevel' in value) || value['spendingLevel'] === undefined) return false;
    return true;
}

export function ApiV2SearchSpendingByGeographyPost200ResponseFromJSON(json: any): ApiV2SearchSpendingByGeographyPost200Response {
    return ApiV2SearchSpendingByGeographyPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2SearchSpendingByGeographyPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchSpendingByGeographyPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'scope': json['scope'] == null ? undefined : json['scope'],
        'geoLayer': json['geo_layer'] == null ? undefined : json['geo_layer'],
        'spendingLevel': json['spending_level'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ApiV2SearchSpendingByGeographyPost200ResponseToJSON(json: any): ApiV2SearchSpendingByGeographyPost200Response {
    return ApiV2SearchSpendingByGeographyPost200ResponseToJSONTyped(json, false);
}

export function ApiV2SearchSpendingByGeographyPost200ResponseToJSONTyped(value?: ApiV2SearchSpendingByGeographyPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scope': value['scope'],
        'geo_layer': value['geoLayer'],
        'spending_level': value['spendingLevel'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ApiV2SearchSpendingByGeographyPost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

