/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInner } from './ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInner';
import {
    ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerFromJSON,
    ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerToJSON,
    ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2AutocompleteAwardingAgencyPost200Response
 */
export interface ApiV2AutocompleteAwardingAgencyPost200Response {
    /**
     * 
     * @type {Array<ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInner>}
     * @memberof ApiV2AutocompleteAwardingAgencyPost200Response
     */
    results: Array<ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AutocompleteAwardingAgencyPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AutocompleteAwardingAgencyPost200Response interface.
 */
export function instanceOfApiV2AutocompleteAwardingAgencyPost200Response(value: object): value is ApiV2AutocompleteAwardingAgencyPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AutocompleteAwardingAgencyPost200ResponseFromJSON(json: any): ApiV2AutocompleteAwardingAgencyPost200Response {
    return ApiV2AutocompleteAwardingAgencyPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompleteAwardingAgencyPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'],
    };
}

export function ApiV2AutocompleteAwardingAgencyPost200ResponseToJSON(json: any): ApiV2AutocompleteAwardingAgencyPost200Response {
    return ApiV2AutocompleteAwardingAgencyPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AutocompleteAwardingAgencyPost200ResponseToJSONTyped(value?: ApiV2AutocompleteAwardingAgencyPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2AutocompleteAwardingAgencyPost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

