/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient
 */
export interface ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient
     */
    recipientName: string;
}

/**
 * Check if a given object implements the ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient interface.
 */
export function instanceOfApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient(value: object): value is ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient {
    if (!('recipientName' in value) || value['recipientName'] === undefined) return false;
    return true;
}

export function ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientFromJSON(json: any): ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient {
    return ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientFromJSONTyped(json, false);
}

export function ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient {
    if (json == null) {
        return json;
    }
    return {
        
        'recipientName': json['recipient_name'],
    };
}

export function ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientToJSON(json: any): ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient {
    return ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientToJSONTyped(json, false);
}

export function ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipientToJSONTyped(value?: ApiV2AwardSpendingRecipientPost200ResponseResultsInnerRecipient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient_name': value['recipientName'],
    };
}

