/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner
 */
export interface ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner
     */
    parentName: string | null;
    /**
     * DUNS number
     * @type {string}
     * @memberof ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner
     */
    parentDuns: string | null;
    /**
     * A unique identifier for the parent recipient.
     * @type {string}
     * @memberof ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner
     */
    parentId: string | null;
    /**
     * Parent recipient's UEI (Unique Entity Identifier). `null` when no UEI is provided.
     * @type {string}
     * @memberof ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner
     */
    parentUei: string | null;
}

/**
 * Check if a given object implements the ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner interface.
 */
export function instanceOfApiV2RecipientDunsRecipientIdPost200ResponseParentsInner(value: object): value is ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner {
    if (!('parentName' in value) || value['parentName'] === undefined) return false;
    if (!('parentDuns' in value) || value['parentDuns'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('parentUei' in value) || value['parentUei'] === undefined) return false;
    return true;
}

export function ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerFromJSON(json: any): ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner {
    return ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerFromJSONTyped(json, false);
}

export function ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'parentName': json['parent_name'],
        'parentDuns': json['parent_duns'],
        'parentId': json['parent_id'],
        'parentUei': json['parent_uei'],
    };
}

export function ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerToJSON(json: any): ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner {
    return ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerToJSONTyped(json, false);
}

export function ApiV2RecipientDunsRecipientIdPost200ResponseParentsInnerToJSONTyped(value?: ApiV2RecipientDunsRecipientIdPost200ResponseParentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parent_name': value['parentName'],
        'parent_duns': value['parentDuns'],
        'parent_id': value['parentId'],
        'parent_uei': value['parentUei'],
    };
}

