/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2IdvsAwardsPost200ResponseResultsInner } from './ApiV2IdvsAwardsPost200ResponseResultsInner';
import {
    ApiV2IdvsAwardsPost200ResponseResultsInnerFromJSON,
    ApiV2IdvsAwardsPost200ResponseResultsInnerFromJSONTyped,
    ApiV2IdvsAwardsPost200ResponseResultsInnerToJSON,
    ApiV2IdvsAwardsPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2IdvsAwardsPost200ResponseResultsInner';
import type { ApiV2AwardsFundingPost200ResponsePageMetadata } from './ApiV2AwardsFundingPost200ResponsePageMetadata';
import {
    ApiV2AwardsFundingPost200ResponsePageMetadataFromJSON,
    ApiV2AwardsFundingPost200ResponsePageMetadataFromJSONTyped,
    ApiV2AwardsFundingPost200ResponsePageMetadataToJSON,
    ApiV2AwardsFundingPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AwardsFundingPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2IdvsAwardsPost200Response
 */
export interface ApiV2IdvsAwardsPost200Response {
    /**
     * 
     * @type {Array<ApiV2IdvsAwardsPost200ResponseResultsInner>}
     * @memberof ApiV2IdvsAwardsPost200Response
     */
    results: Array<ApiV2IdvsAwardsPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2AwardsFundingPost200ResponsePageMetadata}
     * @memberof ApiV2IdvsAwardsPost200Response
     */
    pageMetadata: ApiV2AwardsFundingPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2IdvsAwardsPost200Response interface.
 */
export function instanceOfApiV2IdvsAwardsPost200Response(value: object): value is ApiV2IdvsAwardsPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2IdvsAwardsPost200ResponseFromJSON(json: any): ApiV2IdvsAwardsPost200Response {
    return ApiV2IdvsAwardsPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2IdvsAwardsPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2IdvsAwardsPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2IdvsAwardsPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2AwardsFundingPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2IdvsAwardsPost200ResponseToJSON(json: any): ApiV2IdvsAwardsPost200Response {
    return ApiV2IdvsAwardsPost200ResponseToJSONTyped(json, false);
}

export function ApiV2IdvsAwardsPost200ResponseToJSONTyped(value?: ApiV2IdvsAwardsPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2IdvsAwardsPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2AwardsFundingPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

