/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod } from './ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod';
import {
    ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSON,
    ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSONTyped,
    ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSON,
    ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSONTyped,
} from './ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod';

/**
 * 
 * @export
 * @interface ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner
 */
export interface ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner {
    /**
     * 
     * @type {ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod}
     * @memberof ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner
     */
    timePeriod: ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriod;
    /**
     * The count of new awards for this time period and the given filters.
     * @type {number}
     * @memberof ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner
     */
    newAwardCountInPeriod: number;
}

/**
 * Check if a given object implements the ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner interface.
 */
export function instanceOfApiV2SearchNewAwardsOverTimePost200ResponseResultsInner(value: object): value is ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner {
    if (!('timePeriod' in value) || value['timePeriod'] === undefined) return false;
    if (!('newAwardCountInPeriod' in value) || value['newAwardCountInPeriod'] === undefined) return false;
    return true;
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerFromJSON(json: any): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner {
    return ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timePeriod': ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodFromJSON(json['time_period']),
        'newAwardCountInPeriod': json['new_award_count_in_period'],
    };
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerToJSON(json: any): ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner {
    return ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerToJSONTyped(value?: ApiV2SearchNewAwardsOverTimePost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time_period': ApiV2SearchNewAwardsOverTimePost200ResponseResultsInnerTimePeriodToJSON(value['timePeriod']),
        'new_award_count_in_period': value['newAwardCountInPeriod'],
    };
}

