/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AutocompletePscPost200ResponseResultsInner } from './ApiV2AutocompletePscPost200ResponseResultsInner';
import {
    ApiV2AutocompletePscPost200ResponseResultsInnerFromJSON,
    ApiV2AutocompletePscPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AutocompletePscPost200ResponseResultsInnerToJSON,
    ApiV2AutocompletePscPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AutocompletePscPost200ResponseResultsInner';

/**
 * 
 * @export
 * @interface ApiV2AutocompletePscPost200Response
 */
export interface ApiV2AutocompletePscPost200Response {
    /**
     * 
     * @type {Array<ApiV2AutocompletePscPost200ResponseResultsInner>}
     * @memberof ApiV2AutocompletePscPost200Response
     */
    results: Array<ApiV2AutocompletePscPost200ResponseResultsInner>;
}

/**
 * Check if a given object implements the ApiV2AutocompletePscPost200Response interface.
 */
export function instanceOfApiV2AutocompletePscPost200Response(value: object): value is ApiV2AutocompletePscPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ApiV2AutocompletePscPost200ResponseFromJSON(json: any): ApiV2AutocompletePscPost200Response {
    return ApiV2AutocompletePscPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AutocompletePscPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AutocompletePscPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2AutocompletePscPost200ResponseResultsInnerFromJSON)),
    };
}

export function ApiV2AutocompletePscPost200ResponseToJSON(json: any): ApiV2AutocompletePscPost200Response {
    return ApiV2AutocompletePscPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AutocompletePscPost200ResponseToJSONTyped(value?: ApiV2AutocompletePscPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2AutocompletePscPost200ResponseResultsInnerToJSON)),
    };
}

