/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInner } from './ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInner';
import {
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerFromJSON,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerFromJSONTyped,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerToJSON,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInner';
import type { ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadata } from './ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadata';
import {
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataFromJSON,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataFromJSONTyped,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataToJSON,
    ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response
 */
export interface ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response {
    /**
     * 
     * @type {Array<ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInner>}
     * @memberof ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response
     */
    results: Array<ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInner>;
    /**
     * 
     * @type {ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadata}
     * @memberof ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response
     */
    pageMetadata: ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadata;
}

/**
 * Check if a given object implements the ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response interface.
 */
export function instanceOfApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response(value: object): value is ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    return true;
}

export function ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseFromJSON(json: any): ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response {
    return ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerFromJSON)),
        'pageMetadata': ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataFromJSON(json['page_metadata']),
    };
}

export function ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseToJSON(json: any): ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response {
    return ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseToJSONTyped(json, false);
}

export function ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseToJSONTyped(value?: ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponseResultsInnerToJSON)),
        'page_metadata': ApiV2FederalAccountsFederalAccountCodeObjectClassesTotalPost200ResponsePageMetadataToJSON(value['pageMetadata']),
    };
}

