/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response
 */
export interface ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response
     */
    unlinkedFileCAwardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response
     */
    unlinkedFileDAwardCount: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response
     */
    totalLinkedAwardCount: number;
}

/**
 * Check if a given object implements the ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response interface.
 */
export function instanceOfApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response(value: object): value is ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response {
    if (!('unlinkedFileCAwardCount' in value) || value['unlinkedFileCAwardCount'] === undefined) return false;
    if (!('unlinkedFileDAwardCount' in value) || value['unlinkedFileDAwardCount'] === undefined) return false;
    if (!('totalLinkedAwardCount' in value) || value['totalLinkedAwardCount'] === undefined) return false;
    return true;
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseFromJSON(json: any): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response {
    return ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseFromJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'unlinkedFileCAwardCount': json['unlinked_file_c_award_count'],
        'unlinkedFileDAwardCount': json['unlinked_file_d_award_count'],
        'totalLinkedAwardCount': json['total_linked_award_count'],
    };
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseToJSON(json: any): ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response {
    return ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseToJSONTyped(json, false);
}

export function ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200ResponseToJSONTyped(value?: ApiV2ReportingAgenciesToptierCodeFiscalYearFiscalPeriodUnlinkedAwardsTypePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unlinked_file_c_award_count': value['unlinkedFileCAwardCount'],
        'unlinked_file_d_award_count': value['unlinkedFileDAwardCount'],
        'total_linked_award_count': value['totalLinkedAwardCount'],
    };
}

