/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 2021-03-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV2DownloadDisasterPost200Response
 */
export interface ApiV2DownloadDisasterPost200Response {
    /**
     * The endpoint used to get the status of a download.
     * @type {string}
     * @memberof ApiV2DownloadDisasterPost200Response
     */
    statusUrl: string;
    /**
     * Is the name of the zipfile containing CSVs that will be generated (with a timestamp suffix).
     * @type {string}
     * @memberof ApiV2DownloadDisasterPost200Response
     */
    fileName: string;
    /**
     * The URL for downloading the zip file containing the generated data files. It might not resolve to a file if the download is in-progress.
     * @type {string}
     * @memberof ApiV2DownloadDisasterPost200Response
     */
    fileUrl: string;
    /**
     * The JSON object used when processing the download.
     * @type {object}
     * @memberof ApiV2DownloadDisasterPost200Response
     */
    downloadRequest: object;
}

/**
 * Check if a given object implements the ApiV2DownloadDisasterPost200Response interface.
 */
export function instanceOfApiV2DownloadDisasterPost200Response(value: object): value is ApiV2DownloadDisasterPost200Response {
    if (!('statusUrl' in value) || value['statusUrl'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    if (!('downloadRequest' in value) || value['downloadRequest'] === undefined) return false;
    return true;
}

export function ApiV2DownloadDisasterPost200ResponseFromJSON(json: any): ApiV2DownloadDisasterPost200Response {
    return ApiV2DownloadDisasterPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2DownloadDisasterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2DownloadDisasterPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusUrl': json['status_url'],
        'fileName': json['file_name'],
        'fileUrl': json['file_url'],
        'downloadRequest': json['download_request'],
    };
}

export function ApiV2DownloadDisasterPost200ResponseToJSON(json: any): ApiV2DownloadDisasterPost200Response {
    return ApiV2DownloadDisasterPost200ResponseToJSONTyped(json, false);
}

export function ApiV2DownloadDisasterPost200ResponseToJSONTyped(value?: ApiV2DownloadDisasterPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status_url': value['statusUrl'],
        'file_name': value['fileName'],
        'file_url': value['fileUrl'],
        'download_request': value['downloadRequest'],
    };
}

