/* tslint:disable */
/* eslint-disable */
/**
 * USASpending API Client Contract
 * Auto-converted from USASpending Draft-04 contracts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInner } from './ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInner';
import {
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerFromJSON,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerFromJSONTyped,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerToJSON,
    ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerToJSONTyped,
} from './ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInner';
import type { ApiV2AgencyAwardsCountPost200ResponsePageMetadata } from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';
import {
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSONTyped,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON,
    ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSONTyped,
} from './ApiV2AgencyAwardsCountPost200ResponsePageMetadata';

/**
 * 
 * @export
 * @interface ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
 */
export interface ApiV2AgencyTreasuryAccountTasObjectClassPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
     */
    treasuryAccountSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
     */
    fiscalYear: number;
    /**
     * 
     * @type {ApiV2AgencyAwardsCountPost200ResponsePageMetadata}
     * @memberof ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
     */
    pageMetadata: ApiV2AgencyAwardsCountPost200ResponsePageMetadata;
    /**
     * 
     * @type {Array<ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInner>}
     * @memberof ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
     */
    results: Array<ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInner>;
    /**
     * An array of warnings or instructional directives to aid consumers of this endpoint with development and debugging.
     * @type {Array<string>}
     * @memberof ApiV2AgencyTreasuryAccountTasObjectClassPost200Response
     */
    messages: Array<string>;
}

/**
 * Check if a given object implements the ApiV2AgencyTreasuryAccountTasObjectClassPost200Response interface.
 */
export function instanceOfApiV2AgencyTreasuryAccountTasObjectClassPost200Response(value: object): value is ApiV2AgencyTreasuryAccountTasObjectClassPost200Response {
    if (!('treasuryAccountSymbol' in value) || value['treasuryAccountSymbol'] === undefined) return false;
    if (!('fiscalYear' in value) || value['fiscalYear'] === undefined) return false;
    if (!('pageMetadata' in value) || value['pageMetadata'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseFromJSON(json: any): ApiV2AgencyTreasuryAccountTasObjectClassPost200Response {
    return ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseFromJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV2AgencyTreasuryAccountTasObjectClassPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'treasuryAccountSymbol': json['treasury_account_symbol'],
        'fiscalYear': json['fiscal_year'],
        'pageMetadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataFromJSON(json['page_metadata']),
        'results': ((json['results'] as Array<any>).map(ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerFromJSON)),
        'messages': json['messages'],
    };
}

export function ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseToJSON(json: any): ApiV2AgencyTreasuryAccountTasObjectClassPost200Response {
    return ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseToJSONTyped(json, false);
}

export function ApiV2AgencyTreasuryAccountTasObjectClassPost200ResponseToJSONTyped(value?: ApiV2AgencyTreasuryAccountTasObjectClassPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'treasury_account_symbol': value['treasuryAccountSymbol'],
        'fiscal_year': value['fiscalYear'],
        'page_metadata': ApiV2AgencyAwardsCountPost200ResponsePageMetadataToJSON(value['pageMetadata']),
        'results': ((value['results'] as Array<any>).map(ApiV2AgencyToptierCodeBudgetFunctionPost200ResponseResultsInnerToJSON)),
        'messages': value['messages'],
    };
}

